Attempts: 5
Exception: >-
  System.ArgumentException: Document not found with ID '123456789-0abc-970-0000-4102soterced. (Parameter 'id')
     at Clarius.OpenLaw.Argentina.SaijClient.ReadDocument(String id, HttpClient http) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 237
     at Clarius.OpenLaw.Argentina.SaijClient.LoadAsync(SearchResult item) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 193
     at Clarius.OpenLaw.Argentina.SyncAction.ExecuteAsync(SaijClient client, FileDocumentRepository targetRepository, Boolean noDebugger) in /_/src/OpenLaw.Commands/Argentina/SyncAction.cs:line 31
Item:
  Id: 123456789-0abc-970-0000-4102soterced
  ContentType: Legislacion
  DocumentType:
    Code: DEC
    Text: Decreto
  Status: Individual, Solo Modificatoria o Sin Eficacia
  Date: 2014-01-23
  Data:
    document:
      metadata:
        uuid: 123456789-0abc-970-0000-4102soterced
        document-content-type: legislacion
        friendly-url:
          subdomain: decreto
          description: 79-nacional-limita-designacion-corporacion-mercado-central-buenos-aires-dn20140000079-2014-01-23
      content:
        mecanografico: 20140000079
        jurisdiccion:
          codigo: C
          descripcion: Nacional
          capital: Capital Federal
          id-pais: 11
        numero-norma: 79
        tipo-norma:
          codigo: DEC
          texto: Decreto
        fecha: 2014-01-23
        standard-normativo: DEC C 000079 2014 01 23
        titulo-norma: Limita designación en la Corporación del Mercado Central de Buenos Aires
        nombre-coloquial: DECRETO NACIONAL 79/2014
        estado: Individual, Solo Modificatoria o Sin Eficacia
        descriptores:
          descriptor:
          - elegido:
              termino: Corporación del Mercado Central de Buenos Aires
            preferido:
              termino: Mercado Central de Buenos Aires
            sinonimos:
              termino:
              - Corporación del Mercado Central de Buenos Aires
              - Corporación del Mercado Central
          - elegido:
              termino: gobierno nacional
            preferido:
              termino: Derecho constitucional/Estado/Estado Nacional/gobierno nacional
            sinonimos:
              termino: gobierno federal
          suggest:
            termino:
            - Derecho constitucional
            - Estado
            - gobierno nacional
            - Corporación del Mercado Central de Buenos Aires (Mercado Central de Buenos Aires)
            - Corporación del Mercado Central (Mercado Central de Buenos Aires)
            - Mercado Central de Buenos Aires
            - gobierno federal (gobierno nacional)
            - Estado Nacional
  Json: >-
    {
      "document": {
        "metadata": {
          "uuid": "123456789-0abc-970-0000-4102soterced",
          "document-content-type": "legislacion",
          "friendly-url": {
            "subdomain": "decreto",
            "description": "79-nacional-limita-designacion-corporacion-mercado-central-buenos-aires-dn20140000079-2014-01-23"
          }
        },
        "content": {
          "mecanografico": 20140000079,
          "jurisdiccion": {
            "codigo": "C",
            "descripcion": "Nacional",
            "capital": "Capital Federal",
            "id-pais": 11
          },
          "numero-norma": 79,
          "tipo-norma": {
            "codigo": "DEC",
            "texto": "Decreto"
          },
          "fecha": "2014-01-23",
          "standard-normativo": "DEC C 000079 2014 01 23",
          "titulo-norma": "Limita designación en la Corporación del Mercado Central de Buenos Aires",
          "nombre-coloquial": "DECRETO NACIONAL 79/2014",
          "estado": "Individual, Solo Modificatoria o Sin Eficacia",
          "descriptores": {
            "descriptor": [
              {
                "elegido": {
                  "termino": "Corporación del Mercado Central de Buenos Aires"
                },
                "preferido": {
                  "termino": "Mercado Central de Buenos Aires"
                },
                "sinonimos": {
                  "termino": [
                    "Corporación del Mercado Central de Buenos Aires",
                    "Corporación del Mercado Central"
                  ]
                }
              },
              {
                "elegido": {
                  "termino": "gobierno nacional"
                },
                "preferido": {
                  "termino": "Derecho constitucional/Estado/Estado Nacional/gobierno nacional"
                },
                "sinonimos": {
                  "termino": "gobierno federal"
                }
              }
            ],
            "suggest": {
              "termino": [
                "Derecho constitucional",
                "Estado",
                "gobierno nacional",
                "Corporación del Mercado Central de Buenos Aires (Mercado Central de Buenos Aires)",
                "Corporación del Mercado Central (Mercado Central de Buenos Aires)",
                "Mercado Central de Buenos Aires",
                "gobierno federal (gobierno nacional)",
                "Estado Nacional"
              ]
            }
          }
        }
      }
    }
  JQ: >-
    {
      "id": "123456789-0abc-970-0000-4102soterced",
      "contentType": "legislacion",
      "documentType": {
        "code": "DEC",
        "text": "Decreto"
      },
      "date": "2014-01-23",
      "status": "Individual, Solo Modificatoria o Sin Eficacia",
      "timestamp": null
    }
  Query:
    Tipo: Decreto
    Jurisdiccion: Nacional