Attempts: 5
Exception: >-
  System.ArgumentException: Invalid document data'. (Parameter 'json')
     at Clarius.OpenLaw.Argentina.Document.ParseAsync(String json) in /_/src/OpenLaw.Commands/Argentina/Document.cs:line 50
     at Clarius.OpenLaw.Argentina.SaijClient.ReadDocument(String id, HttpClient http) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 248
     at Clarius.OpenLaw.Argentina.SaijClient.LoadAsync(SearchResult item) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 193
     at Clarius.OpenLaw.Argentina.SyncAction.ExecuteAsync(SaijClient client, FileDocumentRepository targetRepository, Boolean noDebugger) in /_/src/OpenLaw.Commands/Argentina/SyncAction.cs:line 31
Item:
  Id: 123456789-0abc-078-0000-5202soterced
  ContentType: Legislacion
  DocumentType:
    Code: DEC
    Text: Decreto
  Status: Individual, Solo Modificatoria o Sin Eficacia
  Date: 2025-12-11
  Timestamp: 20251212111636
  Data:
    document:
      metadata:
        uuid: 123456789-0abc-078-0000-5202soterced
        document-content-type: legislacion
        friendly-url:
          subdomain: decreto
          description: 870-nacional-designacion-secretario-asuntos-estrategicos-jefatura-gabinete-ministros-dn20250000870-2025-12-11
      content:
        mecanografico: 20250000870
        estado: Individual, Solo Modificatoria o Sin Eficacia
        tipo-norma:
          codigo: DEC
          texto: Decreto
        numero-norma: 870
        fecha: 2025-12-11
        jurisdiccion:
          codigo: C
          descripcion: Nacional
          capital: Capital Federal
          id-pais: 11
        standard-normativo: DEC C 000870 2025 12 11
        titulo-norma: Designación de Secretario de Asuntos Estratégicos de la Jefatura de Gabinete de Ministros
        nombre-coloquial: DECRETO NACIONAL 870/2025
        publicacion-codificada:
          publicacion-decodificada:
            organismo: Boletín Oficial
            fecha: 2025 12 12
        descriptores:
          descriptor:
          - elegido:
              termino: designación
            preferido:
              termino: Derecho administrativo/Administración Pública/empleo público/ingreso a la función pública/nombramiento
            sinonimos:
              termino:
              - nombramiento de funcionarios
              - nombramiento de empleados públicos
              - nombramiento de funcionarios públicos
              - relación de empleo público
              - función pública
              - designación de funcionarios
              - designación de personal
              - designación
              - designación de funcionarios públicos
          - elegido:
              termino: Jefatura de Gabinete de Ministros
            preferido:
              termino: Derecho constitucional/poderes del Estado/Poder Ejecutivo/ministerios/Jefatura de Gabinete de Ministros
            sinonimos:
              termino: poderes públicos
          suggest:
            termino:
            - ingreso a la función pública
            - nombramiento de funcionarios (nombramiento)
            - designación de personal (nombramiento)
            - función pública (Administración Pública)
            - designación de funcionarios públicos (nombramiento)
            - nombramiento
            - designación de funcionarios (nombramiento)
            - poderes del Estado
            - ministerios
            - Administración Pública
            - Jefatura de Gabinete de Ministros
            - nombramiento de funcionarios públicos (nombramiento)
            - Derecho constitucional
            - nombramiento de empleados públicos (nombramiento)
            - designación (nombramiento)
            - Poder Ejecutivo
            - poderes públicos (poderes del Estado)
            - empleo público
            - relación de empleo público (empleo público)
            - Derecho administrativo
        fecha-umod: 20251212111636
  Json: >-
    {
      "document": {
        "metadata": {
          "uuid": "123456789-0abc-078-0000-5202soterced",
          "document-content-type": "legislacion",
          "friendly-url": {
            "subdomain": "decreto",
            "description": "870-nacional-designacion-secretario-asuntos-estrategicos-jefatura-gabinete-ministros-dn20250000870-2025-12-11"
          }
        },
        "content": {
          "mecanografico": 20250000870,
          "estado": "Individual, Solo Modificatoria o Sin Eficacia",
          "tipo-norma": {
            "codigo": "DEC",
            "texto": "Decreto"
          },
          "numero-norma": 870,
          "fecha": "2025-12-11",
          "jurisdiccion": {
            "codigo": "C",
            "descripcion": "Nacional",
            "capital": "Capital Federal",
            "id-pais": 11
          },
          "standard-normativo": "DEC C 000870 2025 12 11",
          "titulo-norma": "Designación de Secretario de Asuntos Estratégicos de la Jefatura de Gabinete de Ministros",
          "nombre-coloquial": "DECRETO NACIONAL 870/2025",
          "publicacion-codificada": {
            "publicacion-decodificada": {
              "organismo": "Boletín Oficial",
              "fecha": "2025 12 12"
            }
          },
          "descriptores": {
            "descriptor": [
              {
                "elegido": {
                  "termino": "designación"
                },
                "preferido": {
                  "termino": "Derecho administrativo/Administración Pública/empleo público/ingreso a la función pública/nombramiento"
                },
                "sinonimos": {
                  "termino": [
                    "nombramiento de funcionarios",
                    "nombramiento de empleados públicos",
                    "nombramiento de funcionarios públicos",
                    "relación de empleo público",
                    "función pública",
                    "designación de funcionarios",
                    "designación de personal",
                    "designación",
                    "designación de funcionarios públicos"
                  ]
                }
              },
              {
                "elegido": {
                  "termino": "Jefatura de Gabinete de Ministros"
                },
                "preferido": {
                  "termino": "Derecho constitucional/poderes del Estado/Poder Ejecutivo/ministerios/Jefatura de Gabinete de Ministros"
                },
                "sinonimos": {
                  "termino": "poderes públicos"
                }
              }
            ],
            "suggest": {
              "termino": [
                "ingreso a la función pública",
                "nombramiento de funcionarios (nombramiento)",
                "designación de personal (nombramiento)",
                "función pública (Administración Pública)",
                "designación de funcionarios públicos (nombramiento)",
                "nombramiento",
                "designación de funcionarios (nombramiento)",
                "poderes del Estado",
                "ministerios",
                "Administración Pública",
                "Jefatura de Gabinete de Ministros",
                "nombramiento de funcionarios públicos (nombramiento)",
                "Derecho constitucional",
                "nombramiento de empleados públicos (nombramiento)",
                "designación (nombramiento)",
                "Poder Ejecutivo",
                "poderes públicos (poderes del Estado)",
                "empleo público",
                "relación de empleo público (empleo público)",
                "Derecho administrativo"
              ]
            }
          },
          "fecha-umod": 20251212111636
        }
      }
    }
  JQ: >-
    {
      "id": "123456789-0abc-078-0000-5202soterced",
      "contentType": "legislacion",
      "documentType": {
        "code": "DEC",
        "text": "Decreto"
      },
      "date": "2025-12-11",
      "status": "Individual, Solo Modificatoria o Sin Eficacia",
      "timestamp": 20251212111636
    }
  Query:
    Tipo: Decreto
    Jurisdiccion: Nacional