Attempts: 5
Exception: >-
  System.ArgumentException: Document not found with ID '123456789-0abc-890-2000-4102soterced. (Parameter 'id')
     at Clarius.OpenLaw.Argentina.SaijClient.ReadDocument(String id, HttpClient http) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 237
     at Clarius.OpenLaw.Argentina.SaijClient.LoadAsync(SearchResult item) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 193
     at Clarius.OpenLaw.Argentina.SyncAction.ExecuteAsync(SaijClient client, FileDocumentRepository targetRepository, Boolean noDebugger) in /_/src/OpenLaw.Commands/Argentina/SyncAction.cs:line 31
Item:
  Id: 123456789-0abc-890-2000-4102soterced
  ContentType: Legislacion
  DocumentType:
    Code: DEC
    Text: Decreto
  Status: Individual, Solo Modificatoria o Sin Eficacia
  Date: 2014-11-12
  Data:
    document:
      metadata:
        uuid: 123456789-0abc-890-2000-4102soterced
        document-content-type: legislacion
        friendly-url:
          subdomain: decreto
          description: 2098-nacional-prorroga-designaciones-presidencia-nacion-dn20140002098-2014-11-12
      content:
        mecanografico: 20140002098
        jurisdiccion:
          codigo: C
          descripcion: Nacional
          capital: Capital Federal
          id-pais: 11
        numero-norma: 2098
        tipo-norma:
          codigo: DEC
          texto: Decreto
        fecha: 2014-11-12
        standard-normativo: DEC C 002098 2014 11 12
        titulo-norma: Prórroga de designaciones en la Presidencia de la Nación
        nombre-coloquial: DECRETO NACIONAL 2.098/2014
        estado: Individual, Solo Modificatoria o Sin Eficacia
        descriptores:
          descriptor:
          - elegido:
              termino: presidencia de la Nación
            preferido:
              termino: Derecho constitucional/poderes del Estado/Poder Ejecutivo/Poder Ejecutivo Nacional/presidencia de la Nación
            sinonimos:
              termino: poderes públicos
          - elegido:
              termino: Secretaría General de la Presidencia
            preferido:
              termino: Secretaría General de la Presidencia
          - elegido:
              termino: designación transitoria
            preferido:
              termino: Derecho administrativo/Administración Pública/empleo público/agentes de la administración pública/situaciones de revista/personal no permanente/personal transitorio
            sinonimos:
              termino:
              - relación de empleo público
              - personal del Estado
              - agentes de la Administración
              - contratación temporaria
              - agentes transitorios
              - función pública
              - planta transitoria
              - nombramiento provisorio
              - personal del sector público
              - agentes públicos
              - personal de planta temporaria
              - funcionarios y empleados públicos
              - designación transitoria
          - elegido:
              termino: prórroga de la designación
            preferido:
              termino: Derecho administrativo/Administración Pública/empleo público/agentes de la administración pública/situaciones de revista/personal no permanente/personal transitorio/prórroga de la designación
            sinonimos:
              termino:
              - nombramiento provisorio
              - personal del sector público
              - relación de empleo público
              - personal del Estado
              - agentes públicos
              - agentes de la Administración
              - contratación temporaria
              - agentes transitorios
              - personal de planta temporaria
              - funcionarios y empleados públicos
              - función pública
              - planta transitoria
              - designación transitoria
          suggest:
            termino:
            - personal no permanente
            - agentes de la administración pública
            - agentes de la Administración (agentes de la administración pública)
            - personal del sector público (agentes de la administración pública)
            - prórroga de la designación
            - situaciones de revista
            - personal del Estado (agentes de la administración pública)
            - designación transitoria (personal transitorio)
            - nombramiento provisorio (personal transitorio)
            - poderes públicos (poderes del Estado)
            - relación de empleo público (empleo público)
            - funcionarios y empleados públicos (agentes de la administración pública)
            - Derecho administrativo
            - agentes transitorios (personal transitorio)
            - función pública (Administración Pública)
            - presidencia de la Nación
            - poderes del Estado
            - Poder Ejecutivo Nacional
            - Administración Pública
            - Secretaría General de la Presidencia
            - Derecho constitucional
            - agentes públicos (agentes de la administración pública)
            - personal transitorio
            - personal de planta temporaria (personal no permanente)
            - Poder Ejecutivo
            - empleo público
            - planta transitoria (personal transitorio)
            - contratación temporaria (personal no permanente)
  Json: >-
    {
      "document": {
        "metadata": {
          "uuid": "123456789-0abc-890-2000-4102soterced",
          "document-content-type": "legislacion",
          "friendly-url": {
            "subdomain": "decreto",
            "description": "2098-nacional-prorroga-designaciones-presidencia-nacion-dn20140002098-2014-11-12"
          }
        },
        "content": {
          "mecanografico": 20140002098,
          "jurisdiccion": {
            "codigo": "C",
            "descripcion": "Nacional",
            "capital": "Capital Federal",
            "id-pais": 11
          },
          "numero-norma": 2098,
          "tipo-norma": {
            "codigo": "DEC",
            "texto": "Decreto"
          },
          "fecha": "2014-11-12",
          "standard-normativo": "DEC C 002098 2014 11 12",
          "titulo-norma": "Prórroga de designaciones en la Presidencia de la Nación",
          "nombre-coloquial": "DECRETO NACIONAL 2.098/2014",
          "estado": "Individual, Solo Modificatoria o Sin Eficacia",
          "descriptores": {
            "descriptor": [
              {
                "elegido": {
                  "termino": "presidencia de la Nación"
                },
                "preferido": {
                  "termino": "Derecho constitucional/poderes del Estado/Poder Ejecutivo/Poder Ejecutivo Nacional/presidencia de la Nación"
                },
                "sinonimos": {
                  "termino": "poderes públicos"
                }
              },
              {
                "elegido": {
                  "termino": "Secretaría General de la Presidencia"
                },
                "preferido": {
                  "termino": "Secretaría General de la Presidencia"
                },
                "sinonimos": null
              },
              {
                "elegido": {
                  "termino": "designación transitoria"
                },
                "preferido": {
                  "termino": "Derecho administrativo/Administración Pública/empleo público/agentes de la administración pública/situaciones de revista/personal no permanente/personal transitorio"
                },
                "sinonimos": {
                  "termino": [
                    "relación de empleo público",
                    "personal del Estado",
                    "agentes de la Administración",
                    "contratación temporaria",
                    "agentes transitorios",
                    "función pública",
                    "planta transitoria",
                    "nombramiento provisorio",
                    "personal del sector público",
                    "agentes públicos",
                    "personal de planta temporaria",
                    "funcionarios y empleados públicos",
                    "designación transitoria"
                  ]
                }
              },
              {
                "elegido": {
                  "termino": "prórroga de la designación"
                },
                "preferido": {
                  "termino": "Derecho administrativo/Administración Pública/empleo público/agentes de la administración pública/situaciones de revista/personal no permanente/personal transitorio/prórroga de la designación"
                },
                "sinonimos": {
                  "termino": [
                    "nombramiento provisorio",
                    "personal del sector público",
                    "relación de empleo público",
                    "personal del Estado",
                    "agentes públicos",
                    "agentes de la Administración",
                    "contratación temporaria",
                    "agentes transitorios",
                    "personal de planta temporaria",
                    "funcionarios y empleados públicos",
                    "función pública",
                    "planta transitoria",
                    "designación transitoria"
                  ]
                }
              }
            ],
            "suggest": {
              "termino": [
                "personal no permanente",
                "agentes de la administración pública",
                "agentes de la Administración (agentes de la administración pública)",
                "personal del sector público (agentes de la administración pública)",
                "prórroga de la designación",
                "situaciones de revista",
                "personal del Estado (agentes de la administración pública)",
                "designación transitoria (personal transitorio)",
                "nombramiento provisorio (personal transitorio)",
                "poderes públicos (poderes del Estado)",
                "relación de empleo público (empleo público)",
                "funcionarios y empleados públicos (agentes de la administración pública)",
                "Derecho administrativo",
                "agentes transitorios (personal transitorio)",
                "función pública (Administración Pública)",
                "presidencia de la Nación",
                "poderes del Estado",
                "Poder Ejecutivo Nacional",
                "Administración Pública",
                "Secretaría General de la Presidencia",
                "Derecho constitucional",
                "agentes públicos (agentes de la administración pública)",
                "personal transitorio",
                "personal de planta temporaria (personal no permanente)",
                "Poder Ejecutivo",
                "empleo público",
                "planta transitoria (personal transitorio)",
                "contratación temporaria (personal no permanente)"
              ]
            }
          }
        }
      }
    }
  JQ: >-
    {
      "id": "123456789-0abc-890-2000-4102soterced",
      "contentType": "legislacion",
      "documentType": {
        "code": "DEC",
        "text": "Decreto"
      },
      "date": "2014-11-12",
      "status": "Individual, Solo Modificatoria o Sin Eficacia",
      "timestamp": null
    }
  Query:
    Tipo: Decreto
    Jurisdiccion: Nacional