Attempts: 5
Exception: >-
  System.ArgumentException: Document not found with ID '123456789-0abc-442-0000-7102soterced. (Parameter 'id')
     at Clarius.OpenLaw.Argentina.SaijClient.ReadDocument(String id, HttpClient http) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 237
     at Clarius.OpenLaw.Argentina.SaijClient.LoadAsync(SearchResult item) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 193
     at Clarius.OpenLaw.Argentina.SyncAction.ExecuteAsync(SaijClient client, FileDocumentRepository targetRepository, Boolean noDebugger) in /_/src/OpenLaw.Commands/Argentina/SyncAction.cs:line 31
Item:
  Id: 123456789-0abc-442-0000-7102soterced
  ContentType: Legislacion
  DocumentType:
    Code: DEC
    Text: Decreto
  Status: Vigente, de alcance general
  Date: 2017-04-07
  Data:
    document:
      metadata:
        uuid: 123456789-0abc-442-0000-7102soterced
        document-content-type: legislacion
        friendly-url:
          subdomain: decreto
          description: 244-nacional-aprobacion-modelo-contrato-prestamo-fondo-financiero-para-desarrollo-cuenca-plata-fonplata-dn20170000244-2017-04-07
      content:
        mecanografico: 20170000244
        jurisdiccion:
          codigo: C
          descripcion: Nacional
          capital: Capital Federal
          id-pais: 11
        numero-norma: 244
        tipo-norma:
          codigo: DEC
          texto: Decreto
        fecha: 2017-04-07
        standard-normativo: DEC C 000244 2017 04 07
        titulo-norma: Aprobación del Modelo de Contrato de Préstamo con el Fondo Financiero para el Desarrollo de la Cuenca del Plata (Fonplata)
        nombre-coloquial: DECRETO NACIONAL 244/2017
        estado: Vigente, de alcance general
        descriptores:
          descriptor:
          - elegido:
              termino: contrato de préstamo
            preferido:
              termino: Economía y finanzas/sistema financiero/préstamo internacional/contratos de préstamo garantizados
            sinonimos:
              termino:
              - Hacienda y Finanzas
              - préstamos garantizados
              - convenio de préstamo
              - derecho económico financiero
              - contrato de préstamo
              - préstamo bancario internacional
              - derecho financiero
          - elegido:
              termino: Fondo Financiero para el Desarrollo de la Cuenca del Plata
            preferido:
              termino: Fondo Financiero para el Desarrollo de la Cuenca del Plata
          suggest:
            termino:
            - sistema financiero
            - préstamos garantizados (contratos de préstamo garantizados)
            - derecho financiero (Economía y finanzas)
            - préstamo bancario internacional (préstamo internacional)
            - contratos de préstamo garantizados
            - contrato de préstamo (contratos de préstamo garantizados)
            - Hacienda y Finanzas (Economía y finanzas)
            - Fondo Financiero para el Desarrollo de la Cuenca del Plata
            - derecho económico financiero (Economía y finanzas)
            - convenio de préstamo (contratos de préstamo garantizados)
            - préstamo internacional
            - Economía y finanzas
  Json: >-
    {
      "document": {
        "metadata": {
          "uuid": "123456789-0abc-442-0000-7102soterced",
          "document-content-type": "legislacion",
          "friendly-url": {
            "subdomain": "decreto",
            "description": "244-nacional-aprobacion-modelo-contrato-prestamo-fondo-financiero-para-desarrollo-cuenca-plata-fonplata-dn20170000244-2017-04-07"
          }
        },
        "content": {
          "mecanografico": 20170000244,
          "jurisdiccion": {
            "codigo": "C",
            "descripcion": "Nacional",
            "capital": "Capital Federal",
            "id-pais": 11
          },
          "numero-norma": 244,
          "tipo-norma": {
            "codigo": "DEC",
            "texto": "Decreto"
          },
          "fecha": "2017-04-07",
          "standard-normativo": "DEC C 000244 2017 04 07",
          "titulo-norma": "Aprobación del Modelo de Contrato de Préstamo con el Fondo Financiero para el Desarrollo de la Cuenca del Plata (Fonplata)",
          "nombre-coloquial": "DECRETO NACIONAL 244/2017",
          "estado": "Vigente, de alcance general",
          "descriptores": {
            "descriptor": [
              {
                "elegido": {
                  "termino": "contrato de préstamo"
                },
                "preferido": {
                  "termino": "Economía y finanzas/sistema financiero/préstamo internacional/contratos de préstamo garantizados"
                },
                "sinonimos": {
                  "termino": [
                    "Hacienda y Finanzas",
                    "préstamos garantizados",
                    "convenio de préstamo",
                    "derecho económico financiero",
                    "contrato de préstamo",
                    "préstamo bancario internacional",
                    "derecho financiero"
                  ]
                }
              },
              {
                "elegido": {
                  "termino": "Fondo Financiero para el Desarrollo de la Cuenca del Plata"
                },
                "preferido": {
                  "termino": "Fondo Financiero para el Desarrollo de la Cuenca del Plata"
                },
                "sinonimos": null
              }
            ],
            "suggest": {
              "termino": [
                "sistema financiero",
                "préstamos garantizados (contratos de préstamo garantizados)",
                "derecho financiero (Economía y finanzas)",
                "préstamo bancario internacional (préstamo internacional)",
                "contratos de préstamo garantizados",
                "contrato de préstamo (contratos de préstamo garantizados)",
                "Hacienda y Finanzas (Economía y finanzas)",
                "Fondo Financiero para el Desarrollo de la Cuenca del Plata",
                "derecho económico financiero (Economía y finanzas)",
                "convenio de préstamo (contratos de préstamo garantizados)",
                "préstamo internacional",
                "Economía y finanzas"
              ]
            }
          }
        }
      }
    }
  JQ: >-
    {
      "id": "123456789-0abc-442-0000-7102soterced",
      "contentType": "legislacion",
      "documentType": {
        "code": "DEC",
        "text": "Decreto"
      },
      "date": "2017-04-07",
      "status": "Vigente, de alcance general",
      "timestamp": null
    }
  Query:
    Tipo: Decreto
    Jurisdiccion: Nacional