Attempts: 5
Exception: >-
  System.ArgumentException: Document not found with ID '123456789-0abc-921-0000-5202soterced. (Parameter 'id')
     at Clarius.OpenLaw.Argentina.SaijClient.ReadDocument(String id, HttpClient http) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 237
     at Clarius.OpenLaw.Argentina.SaijClient.LoadAsync(SearchResult item) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 193
     at Clarius.OpenLaw.Argentina.SyncAction.ExecuteAsync(SaijClient client, FileDocumentRepository targetRepository, Boolean noDebugger) in /_/src/OpenLaw.Commands/Argentina/SyncAction.cs:line 31
Item:
  Id: 123456789-0abc-921-0000-5202soterced
  ContentType: Legislacion
  DocumentType:
    Code: DEC
    Text: Decreto
  Status: Vigente, de alcance general
  Date: 2025-02-25
  Timestamp: 20250226133828
  Data:
    document:
      metadata:
        uuid: 123456789-0abc-921-0000-5202soterced
        document-content-type: legislacion
        friendly-url:
          subdomain: decreto
          description: 129-nacional-intervencion-obra-social-fotografos-180-dias-dn20250000129-2025-02-25
      content:
        mecanografico: 20250000129
        estado: Vigente, de alcance general
        tipo-norma:
          codigo: DEC
          texto: Decreto
        numero-norma: 129
        fecha: 2025-02-25
        jurisdiccion:
          codigo: C
          descripcion: Nacional
          capital: Capital Federal
          id-pais: 11
        standard-normativo: DEC C 000129 2025 02 25
        titulo-norma: Intervención de la Obra Social de Fotógrafos por 180 días
        nombre-coloquial: DECRETO NACIONAL 129/2025
        publicacion-codificada:
          publicacion-decodificada:
            organismo: Boletín Oficial
            fecha: 2025 02 26
        descriptores:
          descriptor:
          - elegido:
              termino: intervención estatal
            preferido:
              termino: Derecho administrativo/sujetos de derecho administrativo/entes descentralizados/entes autárquicos/intervención estatal
            sinonimos:
              termino:
              - administración descentralizada
              - entidades autárquicas
              - organismos descentralizados
              - organismos autárquicos
          - elegido:
              termino: obras sociales
            preferido:
              termino: Seguridad social/derecho de los beneficios de la seguridad social/Régimen Nacional de Obras Sociales/obras sociales
            sinonimos:
              termino: derecho previsional
          - elegido:
              termino: interventor
            preferido:
              termino: Derecho administrativo/poder de policía/control estatal/interventor
            sinonimos:
              termino: control del Estado
          suggest:
            termino:
            - intervención estatal
            - derecho previsional (derecho de los beneficios de la seguridad social)
            - Seguridad social
            - control estatal
            - Régimen Nacional de Obras Sociales
            - obras sociales
            - organismos descentralizados (entes descentralizados)
            - sujetos de derecho administrativo
            - poder de policía
            - administración descentralizada (entes descentralizados)
            - derecho de los beneficios de la seguridad social
            - interventor
            - organismos autárquicos (entes autárquicos)
            - control del Estado (control estatal)
            - entidades autárquicas (entes autárquicos)
            - entes descentralizados
            - Derecho administrativo
            - entes autárquicos
        fecha-umod: 20250226133828
  Json: >-
    {
      "document": {
        "metadata": {
          "uuid": "123456789-0abc-921-0000-5202soterced",
          "document-content-type": "legislacion",
          "friendly-url": {
            "subdomain": "decreto",
            "description": "129-nacional-intervencion-obra-social-fotografos-180-dias-dn20250000129-2025-02-25"
          }
        },
        "content": {
          "mecanografico": 20250000129,
          "estado": "Vigente, de alcance general",
          "tipo-norma": {
            "codigo": "DEC",
            "texto": "Decreto"
          },
          "numero-norma": 129,
          "fecha": "2025-02-25",
          "jurisdiccion": {
            "codigo": "C",
            "descripcion": "Nacional",
            "capital": "Capital Federal",
            "id-pais": 11
          },
          "standard-normativo": "DEC C 000129 2025 02 25",
          "titulo-norma": "Intervención de la Obra Social de Fotógrafos por 180 días",
          "nombre-coloquial": "DECRETO NACIONAL 129/2025",
          "publicacion-codificada": {
            "publicacion-decodificada": {
              "organismo": "Boletín Oficial",
              "fecha": "2025 02 26"
            }
          },
          "descriptores": {
            "descriptor": [
              {
                "elegido": {
                  "termino": "intervención estatal"
                },
                "preferido": {
                  "termino": "Derecho administrativo/sujetos de derecho administrativo/entes descentralizados/entes autárquicos/intervención estatal"
                },
                "sinonimos": {
                  "termino": [
                    "administración descentralizada",
                    "entidades autárquicas",
                    "organismos descentralizados",
                    "organismos autárquicos"
                  ]
                }
              },
              {
                "elegido": {
                  "termino": "obras sociales"
                },
                "preferido": {
                  "termino": "Seguridad social/derecho de los beneficios de la seguridad social/Régimen Nacional de Obras Sociales/obras sociales"
                },
                "sinonimos": {
                  "termino": "derecho previsional"
                }
              },
              {
                "elegido": {
                  "termino": "interventor"
                },
                "preferido": {
                  "termino": "Derecho administrativo/poder de policía/control estatal/interventor"
                },
                "sinonimos": {
                  "termino": "control del Estado"
                }
              }
            ],
            "suggest": {
              "termino": [
                "intervención estatal",
                "derecho previsional (derecho de los beneficios de la seguridad social)",
                "Seguridad social",
                "control estatal",
                "Régimen Nacional de Obras Sociales",
                "obras sociales",
                "organismos descentralizados (entes descentralizados)",
                "sujetos de derecho administrativo",
                "poder de policía",
                "administración descentralizada (entes descentralizados)",
                "derecho de los beneficios de la seguridad social",
                "interventor",
                "organismos autárquicos (entes autárquicos)",
                "control del Estado (control estatal)",
                "entidades autárquicas (entes autárquicos)",
                "entes descentralizados",
                "Derecho administrativo",
                "entes autárquicos"
              ]
            }
          },
          "fecha-umod": 20250226133828
        }
      }
    }
  JQ: >-
    {
      "id": "123456789-0abc-921-0000-5202soterced",
      "contentType": "legislacion",
      "documentType": {
        "code": "DEC",
        "text": "Decreto"
      },
      "date": "2025-02-25",
      "status": "Vigente, de alcance general",
      "timestamp": 20250226133828
    }
  Query:
    Tipo: Decreto
    Jurisdiccion: Nacional