Attempts: 5
Exception: >-
  System.ArgumentException: Document not found with ID '123456789-0abc-710-2000-5102soterced. (Parameter 'id')
     at Clarius.OpenLaw.Argentina.SaijClient.ReadDocument(String id, HttpClient http) in /_/src/OpenLaw/Argentina/SaijClient.cs:line 173
     at Clarius.OpenLaw.Argentina.SaijClient.LoadAsync(SearchResult item) in /_/src/OpenLaw/Argentina/SaijClient.cs:line 129
     at Clarius.OpenLaw.Argentina.SyncCommand.SyncAction.ExecuteAsync(SaijClient client, FileDocumentRepository targetRepository, Boolean noDebugger) in /_/src/OpenLaw/Argentina/SyncCommand.cs:line 288
Item:
  Id: 123456789-0abc-710-2000-5102soterced
  ContentType: Legislacion
  DocumentType:
    Code: DEC
    Text: Decreto
  Status: Individual, Solo Modificatoria o Sin Eficacia
  Date: 2015-09-24
  Data:
    document:
      metadata:
        uuid: 123456789-0abc-710-2000-5102soterced
        document-content-type: legislacion
        friendly-url:
          subdomain: decreto
          description: 2017-nacional-designacion-transitoria-funciones-ministerio-ciencia-tecnologia-innovacion-productiva-dn20150002017-2015-09-24
      content:
        mecanografico: 20150002017
        jurisdiccion:
          codigo: C
          descripcion: Nacional
          capital: Capital Federal
          id-pais: 11
        numero-norma: 2017
        tipo-norma:
          codigo: DEC
          texto: Decreto
        fecha: 2015-09-24
        standard-normativo: DEC C 002017 2015 09 24
        titulo-norma: Designación transitoria de funciones en el Ministerio de Ciencia Tecnología e Innovación Productiva
        nombre-coloquial: DECRETO NACIONAL 2.017/2015
        estado: Individual, Solo Modificatoria o Sin Eficacia
        descriptores:
          descriptor:
          - elegido:
              termino: Ministerio de Ciencia, Tecnología e Innovación Productiva
            preferido:
              termino: Ministerio de Ciencia, Tecnología e Innovación Productiva
          - elegido:
              termino: Consejo Nacional de Investigaciones Científicas y Técnicas
            preferido:
              termino: Consejo Nacional de Investigaciones Científicas y Técnicas
            sinonimos:
              termino: CONICET
          - elegido:
              termino: designación transitoria
            preferido:
              termino: Derecho administrativo/Administración Pública/empleo público/agentes de la administración pública/situaciones de revista/personal no permanente/personal transitorio
            sinonimos:
              termino:
              - relación de empleo público
              - personal del Estado
              - agentes de la Administración
              - contratación temporaria
              - agentes transitorios
              - función pública
              - planta transitoria
              - nombramiento provisorio
              - personal del sector público
              - agentes públicos
              - personal de planta temporaria
              - funcionarios y empleados públicos
              - designación transitoria
          suggest:
            termino:
            - personal no permanente
            - función pública (Administración Pública)
            - Ministerio de Ciencia, Tecnología e Innovación Productiva
            - agentes de la administración pública
            - agentes de la Administración (agentes de la administración pública)
            - Administración Pública
            - agentes públicos (agentes de la administración pública)
            - personal del sector público (agentes de la administración pública)
            - personal transitorio
            - personal de planta temporaria (personal no permanente)
            - designación transitoria (personal transitorio)
            - personal del Estado (agentes de la administración pública)
            - situaciones de revista
            - Consejo Nacional de Investigaciones Científicas y Técnicas
            - nombramiento provisorio (personal transitorio)
            - CONICET (Consejo Nacional de Investigaciones Científicas y Técnicas)
            - empleo público
            - planta transitoria (personal transitorio)
            - relación de empleo público (empleo público)
            - funcionarios y empleados públicos (agentes de la administración pública)
            - Derecho administrativo
            - agentes transitorios (personal transitorio)
            - contratación temporaria (personal no permanente)
  Json: >-
    {
      "document": {
        "metadata": {
          "uuid": "123456789-0abc-710-2000-5102soterced",
          "document-content-type": "legislacion",
          "friendly-url": {
            "subdomain": "decreto",
            "description": "2017-nacional-designacion-transitoria-funciones-ministerio-ciencia-tecnologia-innovacion-productiva-dn20150002017-2015-09-24"
          }
        },
        "content": {
          "mecanografico": 20150002017,
          "jurisdiccion": {
            "codigo": "C",
            "descripcion": "Nacional",
            "capital": "Capital Federal",
            "id-pais": 11
          },
          "numero-norma": 2017,
          "tipo-norma": {
            "codigo": "DEC",
            "texto": "Decreto"
          },
          "fecha": "2015-09-24",
          "standard-normativo": "DEC C 002017 2015 09 24",
          "titulo-norma": "Designación transitoria de funciones en el Ministerio de Ciencia Tecnología e Innovación Productiva",
          "nombre-coloquial": "DECRETO NACIONAL 2.017/2015",
          "estado": "Individual, Solo Modificatoria o Sin Eficacia",
          "descriptores": {
            "descriptor": [
              {
                "elegido": {
                  "termino": "Ministerio de Ciencia, Tecnología e Innovación Productiva"
                },
                "preferido": {
                  "termino": "Ministerio de Ciencia, Tecnología e Innovación Productiva"
                },
                "sinonimos": null
              },
              {
                "elegido": {
                  "termino": "Consejo Nacional de Investigaciones Científicas y Técnicas"
                },
                "preferido": {
                  "termino": "Consejo Nacional de Investigaciones Científicas y Técnicas"
                },
                "sinonimos": {
                  "termino": "CONICET"
                }
              },
              {
                "elegido": {
                  "termino": "designación transitoria"
                },
                "preferido": {
                  "termino": "Derecho administrativo/Administración Pública/empleo público/agentes de la administración pública/situaciones de revista/personal no permanente/personal transitorio"
                },
                "sinonimos": {
                  "termino": [
                    "relación de empleo público",
                    "personal del Estado",
                    "agentes de la Administración",
                    "contratación temporaria",
                    "agentes transitorios",
                    "función pública",
                    "planta transitoria",
                    "nombramiento provisorio",
                    "personal del sector público",
                    "agentes públicos",
                    "personal de planta temporaria",
                    "funcionarios y empleados públicos",
                    "designación transitoria"
                  ]
                }
              }
            ],
            "suggest": {
              "termino": [
                "personal no permanente",
                "función pública (Administración Pública)",
                "Ministerio de Ciencia, Tecnología e Innovación Productiva",
                "agentes de la administración pública",
                "agentes de la Administración (agentes de la administración pública)",
                "Administración Pública",
                "agentes públicos (agentes de la administración pública)",
                "personal del sector público (agentes de la administración pública)",
                "personal transitorio",
                "personal de planta temporaria (personal no permanente)",
                "designación transitoria (personal transitorio)",
                "personal del Estado (agentes de la administración pública)",
                "situaciones de revista",
                "Consejo Nacional de Investigaciones Científicas y Técnicas",
                "nombramiento provisorio (personal transitorio)",
                "CONICET (Consejo Nacional de Investigaciones Científicas y Técnicas)",
                "empleo público",
                "planta transitoria (personal transitorio)",
                "relación de empleo público (empleo público)",
                "funcionarios y empleados públicos (agentes de la administración pública)",
                "Derecho administrativo",
                "agentes transitorios (personal transitorio)",
                "contratación temporaria (personal no permanente)"
              ]
            }
          }
        }
      }
    }
  JQ: >-
    {
      "id": "123456789-0abc-710-2000-5102soterced",
      "contentType": "legislacion",
      "documentType": {
        "code": "DEC",
        "text": "Decreto"
      },
      "date": "2015-09-24",
      "status": "Individual, Solo Modificatoria o Sin Eficacia",
      "timestamp": null
    }
  Query:
    Tipo: Decreto
    Jurisdiccion: Nacional