Attempts: 5
Exception: >-
  System.ArgumentException: Document not found with ID '123456789-0abc-540-2000-4102soterced. (Parameter 'id')
     at Clarius.OpenLaw.Argentina.SaijClient.ReadDocument(String id, HttpClient http) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 237
     at Clarius.OpenLaw.Argentina.SaijClient.LoadAsync(SearchResult item) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 193
     at Clarius.OpenLaw.Argentina.SyncAction.ExecuteAsync(SaijClient client, FileDocumentRepository targetRepository, Boolean noDebugger) in /_/src/OpenLaw.Commands/Argentina/SyncAction.cs:line 31
Item:
  Id: 123456789-0abc-540-2000-4102soterced
  ContentType: Legislacion
  DocumentType:
    Code: DEC
    Text: Decreto
  Status: Individual, Solo Modificatoria o Sin Eficacia
  Date: 2014-10-31
  Data:
    document:
      metadata:
        uuid: 123456789-0abc-540-2000-4102soterced
        document-content-type: legislacion
        friendly-url:
          subdomain: decreto
          description: 2045-nacional-designacion-embajador-extraordinario-plenipotenciario-republica-ante-santa-sede-dn20140002045-2014-10-31
      content:
        mecanografico: 20140002045
        jurisdiccion:
          codigo: C
          descripcion: Nacional
          capital: Capital Federal
          id-pais: 11
        numero-norma: 2045
        tipo-norma:
          codigo: DEC
          texto: Decreto
        fecha: 2014-10-31
        standard-normativo: DEC C 002045 2014 10 31
        titulo-norma: Designación del Embajador Extraordinario y Plenipotenciario de la República ante la Santa Sede
        nombre-coloquial: DECRETO NACIONAL 2.045/2014
        estado: Individual, Solo Modificatoria o Sin Eficacia
        descriptores:
          descriptor:
          - elegido:
              termino: Ministerio de Relaciones Exteriores y Culto
            preferido:
              termino: Ministerio de Relaciones Exteriores
            sinonimos:
              termino:
              - Ministerio de Relaciones Exteriores, Comercio Internacional y Culto
              - Ministerio de Relaciones Exteriores y Culto
          - elegido:
              termino: servicio exterior de la Nación
            preferido:
              termino: Derecho internacional/derecho internacional público/relaciones diplomáticas/servicio exterior de la Nación
            sinonimos:
              termino: relaciones exteriores
          - elegido:
              termino: embajadores extraordinarios y plenipotenciarios
            preferido:
              termino: Derecho internacional/derecho internacional público/relaciones diplomáticas/servicio exterior de la Nación/funcionarios del Servicio Exterior de la Nación/agentes diplomáticos y consulares/agentes diplomáticos/embajadas/embajadores
            sinonimos:
              termino:
              - empleados del Servicio Exterior de la Nación
              - relaciones exteriores
              - representaciones diplomáticas
              - embajadores extraordinarios
              - embajadores extraordinarios y plenipotenciarios
              - diplomáticos
          - elegido:
              termino: Santa Sede
            preferido:
              termino: Ciudad del Vaticano
            sinonimos:
              termino:
              - Estado Vaticano
              - Santa Sede
          suggest:
            termino:
            - Santa Sede (Ciudad del Vaticano)
            - Derecho internacional
            - funcionarios del Servicio Exterior de la Nación
            - Estado Vaticano (Ciudad del Vaticano)
            - Ministerio de Relaciones Exteriores
            - Ministerio de Relaciones Exteriores, Comercio Internacional y Culto (Ministerio de Relaciones Exteriores)
            - diplomáticos (agentes diplomáticos)
            - embajadores extraordinarios y plenipotenciarios (embajadores)
            - Ministerio de Relaciones Exteriores y Culto (Ministerio de Relaciones Exteriores)
            - relaciones exteriores (relaciones diplomáticas)
            - relaciones diplomáticas
            - embajadas
            - agentes diplomáticos y consulares
            - empleados del Servicio Exterior de la Nación (funcionarios del Servicio Exterior de la Nación)
            - servicio exterior de la Nación
            - derecho internacional público
            - embajadores extraordinarios (embajadores)
            - Ciudad del Vaticano
            - agentes diplomáticos
            - embajadores
            - representaciones diplomáticas (embajadas)
  Json: >-
    {
      "document": {
        "metadata": {
          "uuid": "123456789-0abc-540-2000-4102soterced",
          "document-content-type": "legislacion",
          "friendly-url": {
            "subdomain": "decreto",
            "description": "2045-nacional-designacion-embajador-extraordinario-plenipotenciario-republica-ante-santa-sede-dn20140002045-2014-10-31"
          }
        },
        "content": {
          "mecanografico": 20140002045,
          "jurisdiccion": {
            "codigo": "C",
            "descripcion": "Nacional",
            "capital": "Capital Federal",
            "id-pais": 11
          },
          "numero-norma": 2045,
          "tipo-norma": {
            "codigo": "DEC",
            "texto": "Decreto"
          },
          "fecha": "2014-10-31",
          "standard-normativo": "DEC C 002045 2014 10 31",
          "titulo-norma": "Designación del Embajador Extraordinario y Plenipotenciario de la República ante la Santa Sede",
          "nombre-coloquial": "DECRETO NACIONAL 2.045/2014",
          "estado": "Individual, Solo Modificatoria o Sin Eficacia",
          "descriptores": {
            "descriptor": [
              {
                "elegido": {
                  "termino": "Ministerio de Relaciones Exteriores y Culto"
                },
                "preferido": {
                  "termino": "Ministerio de Relaciones Exteriores"
                },
                "sinonimos": {
                  "termino": [
                    "Ministerio de Relaciones Exteriores, Comercio Internacional y Culto",
                    "Ministerio de Relaciones Exteriores y Culto"
                  ]
                }
              },
              {
                "elegido": {
                  "termino": "servicio exterior de la Nación"
                },
                "preferido": {
                  "termino": "Derecho internacional/derecho internacional público/relaciones diplomáticas/servicio exterior de la Nación"
                },
                "sinonimos": {
                  "termino": "relaciones exteriores"
                }
              },
              {
                "elegido": {
                  "termino": "embajadores extraordinarios y plenipotenciarios"
                },
                "preferido": {
                  "termino": "Derecho internacional/derecho internacional público/relaciones diplomáticas/servicio exterior de la Nación/funcionarios del Servicio Exterior de la Nación/agentes diplomáticos y consulares/agentes diplomáticos/embajadas/embajadores"
                },
                "sinonimos": {
                  "termino": [
                    "empleados del Servicio Exterior de la Nación",
                    "relaciones exteriores",
                    "representaciones diplomáticas",
                    "embajadores extraordinarios",
                    "embajadores extraordinarios y plenipotenciarios",
                    "diplomáticos"
                  ]
                }
              },
              {
                "elegido": {
                  "termino": "Santa Sede"
                },
                "preferido": {
                  "termino": "Ciudad del Vaticano"
                },
                "sinonimos": {
                  "termino": [
                    "Estado Vaticano",
                    "Santa Sede"
                  ]
                }
              }
            ],
            "suggest": {
              "termino": [
                "Santa Sede (Ciudad del Vaticano)",
                "Derecho internacional",
                "funcionarios del Servicio Exterior de la Nación",
                "Estado Vaticano (Ciudad del Vaticano)",
                "Ministerio de Relaciones Exteriores",
                "Ministerio de Relaciones Exteriores, Comercio Internacional y Culto (Ministerio de Relaciones Exteriores)",
                "diplomáticos (agentes diplomáticos)",
                "embajadores extraordinarios y plenipotenciarios (embajadores)",
                "Ministerio de Relaciones Exteriores y Culto (Ministerio de Relaciones Exteriores)",
                "relaciones exteriores (relaciones diplomáticas)",
                "relaciones diplomáticas",
                "embajadas",
                "agentes diplomáticos y consulares",
                "empleados del Servicio Exterior de la Nación (funcionarios del Servicio Exterior de la Nación)",
                "servicio exterior de la Nación",
                "derecho internacional público",
                "embajadores extraordinarios (embajadores)",
                "Ciudad del Vaticano",
                "agentes diplomáticos",
                "embajadores",
                "representaciones diplomáticas (embajadas)"
              ]
            }
          }
        }
      }
    }
  JQ: >-
    {
      "id": "123456789-0abc-540-2000-4102soterced",
      "contentType": "legislacion",
      "documentType": {
        "code": "DEC",
        "text": "Decreto"
      },
      "date": "2014-10-31",
      "status": "Individual, Solo Modificatoria o Sin Eficacia",
      "timestamp": null
    }
  Query:
    Tipo: Decreto
    Jurisdiccion: Nacional