Attempts: 5
Exception: >-
  System.ArgumentException: Document not found with ID '123456789-0abc-484-0000-6102soterced. (Parameter 'id')
     at Clarius.OpenLaw.Argentina.SaijClient.ReadDocument(String id, HttpClient http) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 237
     at Clarius.OpenLaw.Argentina.SaijClient.LoadAsync(SearchResult item) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 193
     at Clarius.OpenLaw.Argentina.SyncAction.ExecuteAsync(SaijClient client, FileDocumentRepository targetRepository, Boolean noDebugger) in /_/src/OpenLaw.Commands/Argentina/SyncAction.cs:line 31
Item:
  Id: 123456789-0abc-484-0000-6102soterced
  ContentType: Legislacion
  DocumentType:
    Code: DEC
    Text: Decreto
  Status: Individual, Solo Modificatoria o Sin Eficacia
  Date: 2016-03-14
  Data:
    document:
      metadata:
        uuid: 123456789-0abc-484-0000-6102soterced
        document-content-type: legislacion
        friendly-url:
          subdomain: decreto
          description: 484-nacional-designacion-transitoria-director-general-promocion-institucional-dn20160000484-2016-03-14
      content:
        mecanografico: 20160000484
        jurisdiccion:
          codigo: C
          descripcion: Nacional
          capital: Capital Federal
          id-pais: 11
        numero-norma: 484
        tipo-norma:
          codigo: DEC
          texto: Decreto
        fecha: 2016-03-14
        standard-normativo: DEC C 000484 2016 03 14
        titulo-norma: Designación transitoria del Director General de Promoción Institucional
        nombre-coloquial: DECRETO NACIONAL 484/2016
        estado: Individual, Solo Modificatoria o Sin Eficacia
        descriptores:
          descriptor:
          - elegido:
              termino: Secretaría General de la Presidencia
            preferido:
              termino: Secretaría General de la Presidencia
          - elegido:
              termino: designación
            preferido:
              termino: Derecho administrativo/Administración Pública/empleo público/ingreso a la función pública/nombramiento
            sinonimos:
              termino:
              - nombramiento de funcionarios
              - nombramiento de empleados públicos
              - nombramiento de funcionarios públicos
              - relación de empleo público
              - función pública
              - designación de funcionarios
              - designación de personal
              - designación
              - designación de funcionarios públicos
          suggest:
            termino:
            - ingreso a la función pública
            - nombramiento de funcionarios (nombramiento)
            - designación de personal (nombramiento)
            - función pública (Administración Pública)
            - designación de funcionarios públicos (nombramiento)
            - nombramiento
            - designación de funcionarios (nombramiento)
            - Administración Pública
            - Secretaría General de la Presidencia
            - nombramiento de funcionarios públicos (nombramiento)
            - nombramiento de empleados públicos (nombramiento)
            - designación (nombramiento)
            - empleo público
            - relación de empleo público (empleo público)
            - Derecho administrativo
  Json: >-
    {
      "document": {
        "metadata": {
          "uuid": "123456789-0abc-484-0000-6102soterced",
          "document-content-type": "legislacion",
          "friendly-url": {
            "subdomain": "decreto",
            "description": "484-nacional-designacion-transitoria-director-general-promocion-institucional-dn20160000484-2016-03-14"
          }
        },
        "content": {
          "mecanografico": 20160000484,
          "jurisdiccion": {
            "codigo": "C",
            "descripcion": "Nacional",
            "capital": "Capital Federal",
            "id-pais": 11
          },
          "numero-norma": 484,
          "tipo-norma": {
            "codigo": "DEC",
            "texto": "Decreto"
          },
          "fecha": "2016-03-14",
          "standard-normativo": "DEC C 000484 2016 03 14",
          "titulo-norma": "Designación transitoria del Director General de Promoción Institucional",
          "nombre-coloquial": "DECRETO NACIONAL 484/2016",
          "estado": "Individual, Solo Modificatoria o Sin Eficacia",
          "descriptores": {
            "descriptor": [
              {
                "elegido": {
                  "termino": "Secretaría General de la Presidencia"
                },
                "preferido": {
                  "termino": "Secretaría General de la Presidencia"
                },
                "sinonimos": null
              },
              {
                "elegido": {
                  "termino": "designación"
                },
                "preferido": {
                  "termino": "Derecho administrativo/Administración Pública/empleo público/ingreso a la función pública/nombramiento"
                },
                "sinonimos": {
                  "termino": [
                    "nombramiento de funcionarios",
                    "nombramiento de empleados públicos",
                    "nombramiento de funcionarios públicos",
                    "relación de empleo público",
                    "función pública",
                    "designación de funcionarios",
                    "designación de personal",
                    "designación",
                    "designación de funcionarios públicos"
                  ]
                }
              }
            ],
            "suggest": {
              "termino": [
                "ingreso a la función pública",
                "nombramiento de funcionarios (nombramiento)",
                "designación de personal (nombramiento)",
                "función pública (Administración Pública)",
                "designación de funcionarios públicos (nombramiento)",
                "nombramiento",
                "designación de funcionarios (nombramiento)",
                "Administración Pública",
                "Secretaría General de la Presidencia",
                "nombramiento de funcionarios públicos (nombramiento)",
                "nombramiento de empleados públicos (nombramiento)",
                "designación (nombramiento)",
                "empleo público",
                "relación de empleo público (empleo público)",
                "Derecho administrativo"
              ]
            }
          }
        }
      }
    }
  JQ: >-
    {
      "id": "123456789-0abc-484-0000-6102soterced",
      "contentType": "legislacion",
      "documentType": {
        "code": "DEC",
        "text": "Decreto"
      },
      "date": "2016-03-14",
      "status": "Individual, Solo Modificatoria o Sin Eficacia",
      "timestamp": null
    }
  Query:
    Tipo: Decreto
    Jurisdiccion: Nacional