Attempts: 5
Exception: >-
  System.ArgumentException: Document not found with ID '123456789-0abc-221-0000-5202soterced. (Parameter 'id')
     at Clarius.OpenLaw.Argentina.SaijClient.ReadDocument(String id, HttpClient http) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 237
     at Clarius.OpenLaw.Argentina.SaijClient.LoadAsync(SearchResult item) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 193
     at Clarius.OpenLaw.Argentina.SyncAction.ExecuteAsync(SaijClient client, FileDocumentRepository targetRepository, Boolean noDebugger) in /_/src/OpenLaw.Commands/Argentina/SyncAction.cs:line 31
Item:
  Id: 123456789-0abc-221-0000-5202soterced
  ContentType: Legislacion
  DocumentType:
    Code: DEC
    Text: Decreto
  Status: Vigente, de alcance general
  Date: 2025-02-25
  Timestamp: 20250226121530
  Data:
    document:
      metadata:
        uuid: 123456789-0abc-221-0000-5202soterced
        document-content-type: legislacion
        friendly-url:
          subdomain: decreto
          description: 122-nacional-excusacion-procurador-tesoro-nacion-para-intervenir-caso-ypf-dn20250000122-2025-02-25
      content:
        mecanografico: 20250000122
        estado: Vigente, de alcance general
        tipo-norma:
          codigo: DEC
          texto: Decreto
        numero-norma: 122
        fecha: 2025-02-25
        jurisdiccion:
          codigo: C
          descripcion: Nacional
          capital: Capital Federal
          id-pais: 11
        standard-normativo: DEC C 000122 2025 02 25
        titulo-norma: Excusación del Procurador del Tesoro de la Nación para intervenir en el caso de YPF
        nombre-coloquial: DECRETO NACIONAL 122/2025
        publicacion-codificada:
          publicacion-decodificada:
            organismo: Boletín Oficial
            fecha: 2025 02 26
        descriptores:
          descriptor:
          - elegido:
              termino: excusación de funcionario público
            preferido:
              termino: Derecho administrativo/procedimiento administrativo/excusación de funcionario público
            sinonimos:
              termino: proceso administrativo
          - elegido:
              termino: procurador del tesoro de la Nación
            preferido:
              termino: Derecho administrativo/procedimiento administrativo/competencia administrativa/jurisdicción administrativa/Procuración del Tesoro/procurador del tesoro
            sinonimos:
              termino:
              - Procuración del Tesoro de la Nación
              - procurador del tesoro de la Nación
              - proceso administrativo
          - elegido:
              termino: YPF
            preferido:
              termino: YACIMIENTOS PETROLÍFEROS FISCALES
            sinonimos:
              termino: YPF
          - elegido:
              termino: ética pública
            preferido:
              termino: Derecho administrativo/Administración Pública/empleo público/ética de la función pública
            sinonimos:
              termino:
              - código de ética de la función pública
              - relación de empleo público
              - deberes éticos
              - ética pública
              - función pública
          suggest:
            termino:
            - ética pública (ética de la función pública)
            - procurador del tesoro
            - competencia administrativa
            - Procuración del Tesoro
            - función pública (Administración Pública)
            - proceso administrativo (procedimiento administrativo)
            - excusación de funcionario público
            - Procuración del Tesoro de la Nación (Procuración del Tesoro)
            - YACIMIENTOS PETROLÍFEROS FISCALES
            - Administración Pública
            - ética de la función pública
            - YPF (YACIMIENTOS PETROLÍFEROS FISCALES)
            - código de ética de la función pública (ética de la función pública)
            - procurador del tesoro de la Nación (procurador del tesoro)
            - jurisdicción administrativa
            - empleo público
            - relación de empleo público (empleo público)
            - procedimiento administrativo
            - Derecho administrativo
            - deberes éticos (ética de la función pública)
        fecha-umod: 20250226121530
  Json: >-
    {
      "document": {
        "metadata": {
          "uuid": "123456789-0abc-221-0000-5202soterced",
          "document-content-type": "legislacion",
          "friendly-url": {
            "subdomain": "decreto",
            "description": "122-nacional-excusacion-procurador-tesoro-nacion-para-intervenir-caso-ypf-dn20250000122-2025-02-25"
          }
        },
        "content": {
          "mecanografico": 20250000122,
          "estado": "Vigente, de alcance general",
          "tipo-norma": {
            "codigo": "DEC",
            "texto": "Decreto"
          },
          "numero-norma": 122,
          "fecha": "2025-02-25",
          "jurisdiccion": {
            "codigo": "C",
            "descripcion": "Nacional",
            "capital": "Capital Federal",
            "id-pais": 11
          },
          "standard-normativo": "DEC C 000122 2025 02 25",
          "titulo-norma": "Excusación del Procurador del Tesoro de la Nación para intervenir en el caso de YPF",
          "nombre-coloquial": "DECRETO NACIONAL 122/2025",
          "publicacion-codificada": {
            "publicacion-decodificada": {
              "organismo": "Boletín Oficial",
              "fecha": "2025 02 26"
            }
          },
          "descriptores": {
            "descriptor": [
              {
                "elegido": {
                  "termino": "excusación de funcionario público"
                },
                "preferido": {
                  "termino": "Derecho administrativo/procedimiento administrativo/excusación de funcionario público"
                },
                "sinonimos": {
                  "termino": "proceso administrativo"
                }
              },
              {
                "elegido": {
                  "termino": "procurador del tesoro de la Nación"
                },
                "preferido": {
                  "termino": "Derecho administrativo/procedimiento administrativo/competencia administrativa/jurisdicción administrativa/Procuración del Tesoro/procurador del tesoro"
                },
                "sinonimos": {
                  "termino": [
                    "Procuración del Tesoro de la Nación",
                    "procurador del tesoro de la Nación",
                    "proceso administrativo"
                  ]
                }
              },
              {
                "elegido": {
                  "termino": "YPF"
                },
                "preferido": {
                  "termino": "YACIMIENTOS PETROLÍFEROS FISCALES"
                },
                "sinonimos": {
                  "termino": "YPF"
                }
              },
              {
                "elegido": {
                  "termino": "ética pública"
                },
                "preferido": {
                  "termino": "Derecho administrativo/Administración Pública/empleo público/ética de la función pública"
                },
                "sinonimos": {
                  "termino": [
                    "código de ética de la función pública",
                    "relación de empleo público",
                    "deberes éticos",
                    "ética pública",
                    "función pública"
                  ]
                }
              }
            ],
            "suggest": {
              "termino": [
                "ética pública (ética de la función pública)",
                "procurador del tesoro",
                "competencia administrativa",
                "Procuración del Tesoro",
                "función pública (Administración Pública)",
                "proceso administrativo (procedimiento administrativo)",
                "excusación de funcionario público",
                "Procuración del Tesoro de la Nación (Procuración del Tesoro)",
                "YACIMIENTOS PETROLÍFEROS FISCALES",
                "Administración Pública",
                "ética de la función pública",
                "YPF (YACIMIENTOS PETROLÍFEROS FISCALES)",
                "código de ética de la función pública (ética de la función pública)",
                "procurador del tesoro de la Nación (procurador del tesoro)",
                "jurisdicción administrativa",
                "empleo público",
                "relación de empleo público (empleo público)",
                "procedimiento administrativo",
                "Derecho administrativo",
                "deberes éticos (ética de la función pública)"
              ]
            }
          },
          "fecha-umod": 20250226121530
        }
      }
    }
  JQ: >-
    {
      "id": "123456789-0abc-221-0000-5202soterced",
      "contentType": "legislacion",
      "documentType": {
        "code": "DEC",
        "text": "Decreto"
      },
      "date": "2025-02-25",
      "status": "Vigente, de alcance general",
      "timestamp": 20250226121530
    }
  Query:
    Tipo: Decreto
    Jurisdiccion: Nacional