Attempts: 5
Exception: >-
  System.ArgumentException: Invalid document data'. (Parameter 'json')
     at Clarius.OpenLaw.Argentina.Document.ParseAsync(String json) in /_/src/OpenLaw.Commands/Argentina/Document.cs:line 50
     at Clarius.OpenLaw.Argentina.SaijClient.ReadDocument(String id, HttpClient http) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 248
     at Clarius.OpenLaw.Argentina.SaijClient.LoadAsync(SearchResult item) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 193
     at Clarius.OpenLaw.Argentina.SyncAction.ExecuteAsync(SaijClient client, FileDocumentRepository targetRepository, Boolean noDebugger) in /_/src/OpenLaw.Commands/Argentina/SyncAction.cs:line 31
Item:
  Id: 123456789-0abc-478-0000-5202soterced
  ContentType: Legislacion
  DocumentType:
    Code: DEC
    Text: Decreto
  Status: Individual, Solo Modificatoria o Sin Eficacia
  Date: 2025-12-11
  Timestamp: 20251212111547
  Data:
    document:
      metadata:
        uuid: 123456789-0abc-478-0000-5202soterced
        document-content-type: legislacion
        friendly-url:
          subdomain: decreto
          description: 874-nacional-designacion-subsecretario-coordinacion-administrativa-secretaria-gestion-administrativa-ministerio-salud-dn20250000874-2025-12-11
      content:
        mecanografico: 20250000874
        estado: Individual, Solo Modificatoria o Sin Eficacia
        tipo-norma:
          codigo: DEC
          texto: Decreto
        numero-norma: 874
        fecha: 2025-12-11
        jurisdiccion:
          codigo: C
          descripcion: Nacional
          capital: Capital Federal
          id-pais: 11
        standard-normativo: DEC C 000874 2025 12 11
        titulo-norma: Designación de Subsecretario de Coordinación Administrativa de la Secretaría de Gestión Administrativa del Ministerio de Salud
        nombre-coloquial: DECRETO NACIONAL 874/2025
        publicacion-codificada:
          publicacion-decodificada:
            organismo: Boletín Oficial
            fecha: 2025 12 12
        descriptores:
          descriptor:
          - elegido:
              termino: designación
            preferido:
              termino: Derecho administrativo/Administración Pública/empleo público/ingreso a la función pública/nombramiento
            sinonimos:
              termino:
              - nombramiento de funcionarios
              - nombramiento de empleados públicos
              - nombramiento de funcionarios públicos
              - relación de empleo público
              - función pública
              - designación de funcionarios
              - designación de personal
              - designación
              - designación de funcionarios públicos
          - elegido:
              termino: MINISTERIO DE SALUD
            preferido:
              termino: MINISTERIO DE SALUD
            sinonimos:
              termino:
              - Ministerio de Salud Pública y Medio Ambiente
              - Ministerio de Salud y Ambiente
              - Ministerio de Salud y Acción Social
          suggest:
            termino:
            - Ministerio de Salud y Ambiente (MINISTERIO DE SALUD)
            - ingreso a la función pública
            - nombramiento de funcionarios (nombramiento)
            - designación de personal (nombramiento)
            - función pública (Administración Pública)
            - Ministerio de Salud y Acción Social (MINISTERIO DE SALUD)
            - designación de funcionarios públicos (nombramiento)
            - nombramiento
            - designación de funcionarios (nombramiento)
            - Administración Pública
            - Ministerio de Salud Pública y Medio Ambiente (MINISTERIO DE SALUD)
            - nombramiento de funcionarios públicos (nombramiento)
            - MINISTERIO DE SALUD
            - nombramiento de empleados públicos (nombramiento)
            - designación (nombramiento)
            - empleo público
            - relación de empleo público (empleo público)
            - Derecho administrativo
        fecha-umod: 20251212111547
  Json: >-
    {
      "document": {
        "metadata": {
          "uuid": "123456789-0abc-478-0000-5202soterced",
          "document-content-type": "legislacion",
          "friendly-url": {
            "subdomain": "decreto",
            "description": "874-nacional-designacion-subsecretario-coordinacion-administrativa-secretaria-gestion-administrativa-ministerio-salud-dn20250000874-2025-12-11"
          }
        },
        "content": {
          "mecanografico": 20250000874,
          "estado": "Individual, Solo Modificatoria o Sin Eficacia",
          "tipo-norma": {
            "codigo": "DEC",
            "texto": "Decreto"
          },
          "numero-norma": 874,
          "fecha": "2025-12-11",
          "jurisdiccion": {
            "codigo": "C",
            "descripcion": "Nacional",
            "capital": "Capital Federal",
            "id-pais": 11
          },
          "standard-normativo": "DEC C 000874 2025 12 11",
          "titulo-norma": "Designación de Subsecretario de Coordinación Administrativa de la Secretaría de Gestión Administrativa del Ministerio de Salud",
          "nombre-coloquial": "DECRETO NACIONAL 874/2025",
          "publicacion-codificada": {
            "publicacion-decodificada": {
              "organismo": "Boletín Oficial",
              "fecha": "2025 12 12"
            }
          },
          "descriptores": {
            "descriptor": [
              {
                "elegido": {
                  "termino": "designación"
                },
                "preferido": {
                  "termino": "Derecho administrativo/Administración Pública/empleo público/ingreso a la función pública/nombramiento"
                },
                "sinonimos": {
                  "termino": [
                    "nombramiento de funcionarios",
                    "nombramiento de empleados públicos",
                    "nombramiento de funcionarios públicos",
                    "relación de empleo público",
                    "función pública",
                    "designación de funcionarios",
                    "designación de personal",
                    "designación",
                    "designación de funcionarios públicos"
                  ]
                }
              },
              {
                "elegido": {
                  "termino": "MINISTERIO DE SALUD"
                },
                "preferido": {
                  "termino": "MINISTERIO DE SALUD"
                },
                "sinonimos": {
                  "termino": [
                    "Ministerio de Salud Pública y Medio Ambiente",
                    "Ministerio de Salud y Ambiente",
                    "Ministerio de Salud y Acción Social"
                  ]
                }
              }
            ],
            "suggest": {
              "termino": [
                "Ministerio de Salud y Ambiente (MINISTERIO DE SALUD)",
                "ingreso a la función pública",
                "nombramiento de funcionarios (nombramiento)",
                "designación de personal (nombramiento)",
                "función pública (Administración Pública)",
                "Ministerio de Salud y Acción Social (MINISTERIO DE SALUD)",
                "designación de funcionarios públicos (nombramiento)",
                "nombramiento",
                "designación de funcionarios (nombramiento)",
                "Administración Pública",
                "Ministerio de Salud Pública y Medio Ambiente (MINISTERIO DE SALUD)",
                "nombramiento de funcionarios públicos (nombramiento)",
                "MINISTERIO DE SALUD",
                "nombramiento de empleados públicos (nombramiento)",
                "designación (nombramiento)",
                "empleo público",
                "relación de empleo público (empleo público)",
                "Derecho administrativo"
              ]
            }
          },
          "fecha-umod": 20251212111547
        }
      }
    }
  JQ: >-
    {
      "id": "123456789-0abc-478-0000-5202soterced",
      "contentType": "legislacion",
      "documentType": {
        "code": "DEC",
        "text": "Decreto"
      },
      "date": "2025-12-11",
      "status": "Individual, Solo Modificatoria o Sin Eficacia",
      "timestamp": 20251212111547
    }
  Query:
    Tipo: Decreto
    Jurisdiccion: Nacional