Attempts: 5
Exception: >-
  System.ArgumentException: Document not found with ID '123456789-0abc-232-0000-7102soterced. (Parameter 'id')
     at Clarius.OpenLaw.Argentina.SaijClient.ReadDocument(String id, HttpClient http) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 237
     at Clarius.OpenLaw.Argentina.SaijClient.LoadAsync(SearchResult item) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 193
     at Clarius.OpenLaw.Argentina.SyncAction.ExecuteAsync(SaijClient client, FileDocumentRepository targetRepository, Boolean noDebugger) in /_/src/OpenLaw.Commands/Argentina/SyncAction.cs:line 31
Item:
  Id: 123456789-0abc-232-0000-7102soterced
  ContentType: Legislacion
  DocumentType:
    Code: DEC
    Text: Decreto
  Status: Individual, Solo Modificatoria o Sin Eficacia
  Date: 2017-04-06
  Data:
    document:
      metadata:
        uuid: 123456789-0abc-232-0000-7102soterced
        document-content-type: legislacion
        friendly-url:
          subdomain: decreto
          description: 232-nacional-modificacion-decreto-191-2017-dn20170000232-2017-04-06
      content:
        mecanografico: 20170000232
        jurisdiccion:
          codigo: C
          descripcion: Nacional
          capital: Capital Federal
          id-pais: 11
        numero-norma: 232
        tipo-norma:
          codigo: DEC
          texto: Decreto
        fecha: 2017-04-06
        standard-normativo: DEC C 000232 2017 04 06
        titulo-norma: Modificación del Decreto 191/2017
        nombre-coloquial: DECRETO NACIONAL 232/2017
        estado: Individual, Solo Modificatoria o Sin Eficacia
        descriptores:
          descriptor:
          - elegido:
              termino: Ejército
            preferido:
              termino: Defensa y seguridad/derecho militar/Fuerzas Armadas/Ejército
            sinonimos:
              termino: defensa nacional
          - elegido:
              termino: promoción de grado
            preferido:
              termino: Derecho administrativo/Administración Pública/empleo público/agentes de la administración pública/derechos de los agentes de la administración pública/carrera administrativa/escalafón/SINAPA/promoción de grado
            sinonimos:
              termino:
              - personal del sector público
              - derechos del empleado público
              - relación de empleo público
              - personal del Estado
              - agentes públicos
              - agentes de la Administración
              - Sistema Nacional de la Profesión Administrativa
              - derechos del funcionario público
              - funcionarios y empleados públicos
              - función pública
          suggest:
            termino:
            - promoción de grado
            - función pública (Administración Pública)
            - defensa nacional (Defensa y seguridad)
            - SINAPA
            - Sistema Nacional de la Profesión Administrativa (SINAPA)
            - agentes de la administración pública
            - carrera administrativa
            - agentes de la Administración (agentes de la administración pública)
            - derechos del funcionario público (derechos de los agentes de la administración pública)
            - Administración Pública
            - Defensa y seguridad
            - agentes públicos (agentes de la administración pública)
            - derechos de los agentes de la administración pública
            - personal del sector público (agentes de la administración pública)
            - derechos del empleado público (derechos de los agentes de la administración pública)
            - personal del Estado (agentes de la administración pública)
            - derecho militar
            - empleo público
            - escalafón
            - Ejército
            - relación de empleo público (empleo público)
            - funcionarios y empleados públicos (agentes de la administración pública)
            - Derecho administrativo
            - Fuerzas Armadas
  Json: >-
    {
      "document": {
        "metadata": {
          "uuid": "123456789-0abc-232-0000-7102soterced",
          "document-content-type": "legislacion",
          "friendly-url": {
            "subdomain": "decreto",
            "description": "232-nacional-modificacion-decreto-191-2017-dn20170000232-2017-04-06"
          }
        },
        "content": {
          "mecanografico": 20170000232,
          "jurisdiccion": {
            "codigo": "C",
            "descripcion": "Nacional",
            "capital": "Capital Federal",
            "id-pais": 11
          },
          "numero-norma": 232,
          "tipo-norma": {
            "codigo": "DEC",
            "texto": "Decreto"
          },
          "fecha": "2017-04-06",
          "standard-normativo": "DEC C 000232 2017 04 06",
          "titulo-norma": "Modificación del Decreto 191/2017",
          "nombre-coloquial": "DECRETO NACIONAL 232/2017",
          "estado": "Individual, Solo Modificatoria o Sin Eficacia",
          "descriptores": {
            "descriptor": [
              {
                "elegido": {
                  "termino": "Ejército"
                },
                "preferido": {
                  "termino": "Defensa y seguridad/derecho militar/Fuerzas Armadas/Ejército"
                },
                "sinonimos": {
                  "termino": "defensa nacional"
                }
              },
              {
                "elegido": {
                  "termino": "promoción de grado"
                },
                "preferido": {
                  "termino": "Derecho administrativo/Administración Pública/empleo público/agentes de la administración pública/derechos de los agentes de la administración pública/carrera administrativa/escalafón/SINAPA/promoción de grado"
                },
                "sinonimos": {
                  "termino": [
                    "personal del sector público",
                    "derechos del empleado público",
                    "relación de empleo público",
                    "personal del Estado",
                    "agentes públicos",
                    "agentes de la Administración",
                    "Sistema Nacional de la Profesión Administrativa",
                    "derechos del funcionario público",
                    "funcionarios y empleados públicos",
                    "función pública"
                  ]
                }
              }
            ],
            "suggest": {
              "termino": [
                "promoción de grado",
                "función pública (Administración Pública)",
                "defensa nacional (Defensa y seguridad)",
                "SINAPA",
                "Sistema Nacional de la Profesión Administrativa (SINAPA)",
                "agentes de la administración pública",
                "carrera administrativa",
                "agentes de la Administración (agentes de la administración pública)",
                "derechos del funcionario público (derechos de los agentes de la administración pública)",
                "Administración Pública",
                "Defensa y seguridad",
                "agentes públicos (agentes de la administración pública)",
                "derechos de los agentes de la administración pública",
                "personal del sector público (agentes de la administración pública)",
                "derechos del empleado público (derechos de los agentes de la administración pública)",
                "personal del Estado (agentes de la administración pública)",
                "derecho militar",
                "empleo público",
                "escalafón",
                "Ejército",
                "relación de empleo público (empleo público)",
                "funcionarios y empleados públicos (agentes de la administración pública)",
                "Derecho administrativo",
                "Fuerzas Armadas"
              ]
            }
          }
        }
      }
    }
  JQ: >-
    {
      "id": "123456789-0abc-232-0000-7102soterced",
      "contentType": "legislacion",
      "documentType": {
        "code": "DEC",
        "text": "Decreto"
      },
      "date": "2017-04-06",
      "status": "Individual, Solo Modificatoria o Sin Eficacia",
      "timestamp": null
    }
  Query:
    Tipo: Decreto
    Jurisdiccion: Nacional