Attempts: 5
Exception: >-
  System.ArgumentException: Document not found with ID '123456789-0abc-084-0000-4102soterced. (Parameter 'id')
     at Clarius.OpenLaw.Argentina.SaijClient.ReadDocument(String id, HttpClient http) in /_/src/OpenLaw/Argentina/SaijClient.cs:line 172
     at Clarius.OpenLaw.Argentina.SaijClient.LoadAsync(SearchResult item) in /_/src/OpenLaw/Argentina/SaijClient.cs:line 128
     at Clarius.OpenLaw.Argentina.SyncCommand.SyncAction.ExecuteAsync() in /_/src/OpenLaw/Argentina/SyncCommand.cs:line 221
Item:
  Id: 123456789-0abc-084-0000-4102soterced
  ContentType: Legislacion
  DocumentType:
    Code: DEC
    Text: Decreto
  Status: Individual, Solo Modificatoria o Sin Eficacia
  Date: 2014-04-03
  Data:
    document:
      metadata:
        uuid: 123456789-0abc-084-0000-4102soterced
        document-content-type: legislacion
        friendly-url:
          subdomain: decreto
          description: 480-nacional-prorroga-designacion-transitoria-ministerio-educacion-dn20140000480-2014-04-03
      content:
        mecanografico: 20140000480
        jurisdiccion:
          codigo: C
          descripcion: Nacional
          capital: Capital Federal
          id-pais: 11
        numero-norma: 480
        tipo-norma:
          codigo: DEC
          texto: Decreto
        fecha: 2014-04-03
        standard-normativo: DEC C 000480 2014 04 03
        titulo-norma: Prórroga de designación transitoria en el Ministerio de Educación
        nombre-coloquial: DECRETO NACIONAL 480/2014
        estado: Individual, Solo Modificatoria o Sin Eficacia
        descriptores:
          descriptor:
          - elegido:
              termino: Ministerio de Educación
            preferido:
              termino: Ministerio de Educación
            sinonimos:
              termino:
              - Ministerio de Educación y Justicia
              - Ministerio de Educación, Ciencia y Tecnología
              - Ministerio de Cultura y Educación
          - elegido:
              termino: designación transitoria
            preferido:
              termino: Derecho administrativo/Administración Pública/empleo público/agentes de la administración pública/situaciones de revista/personal no permanente/personal transitorio
            sinonimos:
              termino:
              - relación de empleo público
              - personal del Estado
              - agentes de la Administración
              - contratación temporaria
              - agentes transitorios
              - función pública
              - planta transitoria
              - nombramiento provisorio
              - personal del sector público
              - agentes públicos
              - personal de planta temporaria
              - funcionarios y empleados públicos
              - designación transitoria
          - elegido:
              termino: prórroga de la designación
            preferido:
              termino: Derecho administrativo/Administración Pública/empleo público/agentes de la administración pública/situaciones de revista/personal no permanente/personal transitorio/prórroga de la designación
            sinonimos:
              termino:
              - nombramiento provisorio
              - personal del sector público
              - relación de empleo público
              - personal del Estado
              - agentes públicos
              - agentes de la Administración
              - contratación temporaria
              - agentes transitorios
              - personal de planta temporaria
              - funcionarios y empleados públicos
              - función pública
              - planta transitoria
              - designación transitoria
          suggest:
            termino:
            - personal no permanente
            - agentes de la administración pública
            - agentes de la Administración (agentes de la administración pública)
            - personal del sector público (agentes de la administración pública)
            - prórroga de la designación
            - situaciones de revista
            - personal del Estado (agentes de la administración pública)
            - designación transitoria (personal transitorio)
            - nombramiento provisorio (personal transitorio)
            - relación de empleo público (empleo público)
            - funcionarios y empleados públicos (agentes de la administración pública)
            - Ministerio de Cultura y Educación (Ministerio de Educación)
            - Derecho administrativo
            - agentes transitorios (personal transitorio)
            - Ministerio de Educación
            - función pública (Administración Pública)
            - Ministerio de Educación y Justicia (Ministerio de Educación)
            - Administración Pública
            - agentes públicos (agentes de la administración pública)
            - personal transitorio
            - personal de planta temporaria (personal no permanente)
            - empleo público
            - planta transitoria (personal transitorio)
            - Ministerio de Educación, Ciencia y Tecnología (Ministerio de Educación)
            - contratación temporaria (personal no permanente)
  Json: >-
    {
      "document": {
        "metadata": {
          "uuid": "123456789-0abc-084-0000-4102soterced",
          "document-content-type": "legislacion",
          "friendly-url": {
            "subdomain": "decreto",
            "description": "480-nacional-prorroga-designacion-transitoria-ministerio-educacion-dn20140000480-2014-04-03"
          }
        },
        "content": {
          "mecanografico": 20140000480,
          "jurisdiccion": {
            "codigo": "C",
            "descripcion": "Nacional",
            "capital": "Capital Federal",
            "id-pais": 11
          },
          "numero-norma": 480,
          "tipo-norma": {
            "codigo": "DEC",
            "texto": "Decreto"
          },
          "fecha": "2014-04-03",
          "standard-normativo": "DEC C 000480 2014 04 03",
          "titulo-norma": "Prórroga de designación transitoria en el Ministerio de Educación",
          "nombre-coloquial": "DECRETO NACIONAL 480/2014",
          "estado": "Individual, Solo Modificatoria o Sin Eficacia",
          "descriptores": {
            "descriptor": [
              {
                "elegido": {
                  "termino": "Ministerio de Educación"
                },
                "preferido": {
                  "termino": "Ministerio de Educación"
                },
                "sinonimos": {
                  "termino": [
                    "Ministerio de Educación y Justicia",
                    "Ministerio de Educación, Ciencia y Tecnología",
                    "Ministerio de Cultura y Educación"
                  ]
                }
              },
              {
                "elegido": {
                  "termino": "designación transitoria"
                },
                "preferido": {
                  "termino": "Derecho administrativo/Administración Pública/empleo público/agentes de la administración pública/situaciones de revista/personal no permanente/personal transitorio"
                },
                "sinonimos": {
                  "termino": [
                    "relación de empleo público",
                    "personal del Estado",
                    "agentes de la Administración",
                    "contratación temporaria",
                    "agentes transitorios",
                    "función pública",
                    "planta transitoria",
                    "nombramiento provisorio",
                    "personal del sector público",
                    "agentes públicos",
                    "personal de planta temporaria",
                    "funcionarios y empleados públicos",
                    "designación transitoria"
                  ]
                }
              },
              {
                "elegido": {
                  "termino": "prórroga de la designación"
                },
                "preferido": {
                  "termino": "Derecho administrativo/Administración Pública/empleo público/agentes de la administración pública/situaciones de revista/personal no permanente/personal transitorio/prórroga de la designación"
                },
                "sinonimos": {
                  "termino": [
                    "nombramiento provisorio",
                    "personal del sector público",
                    "relación de empleo público",
                    "personal del Estado",
                    "agentes públicos",
                    "agentes de la Administración",
                    "contratación temporaria",
                    "agentes transitorios",
                    "personal de planta temporaria",
                    "funcionarios y empleados públicos",
                    "función pública",
                    "planta transitoria",
                    "designación transitoria"
                  ]
                }
              }
            ],
            "suggest": {
              "termino": [
                "personal no permanente",
                "agentes de la administración pública",
                "agentes de la Administración (agentes de la administración pública)",
                "personal del sector público (agentes de la administración pública)",
                "prórroga de la designación",
                "situaciones de revista",
                "personal del Estado (agentes de la administración pública)",
                "designación transitoria (personal transitorio)",
                "nombramiento provisorio (personal transitorio)",
                "relación de empleo público (empleo público)",
                "funcionarios y empleados públicos (agentes de la administración pública)",
                "Ministerio de Cultura y Educación (Ministerio de Educación)",
                "Derecho administrativo",
                "agentes transitorios (personal transitorio)",
                "Ministerio de Educación",
                "función pública (Administración Pública)",
                "Ministerio de Educación y Justicia (Ministerio de Educación)",
                "Administración Pública",
                "agentes públicos (agentes de la administración pública)",
                "personal transitorio",
                "personal de planta temporaria (personal no permanente)",
                "empleo público",
                "planta transitoria (personal transitorio)",
                "Ministerio de Educación, Ciencia y Tecnología (Ministerio de Educación)",
                "contratación temporaria (personal no permanente)"
              ]
            }
          }
        }
      }
    }
  JQ: >-
    {
      "id": "123456789-0abc-084-0000-4102soterced",
      "contentType": "legislacion",
      "documentType": {
        "code": "DEC",
        "text": "Decreto"
      },
      "date": "2014-04-03",
      "status": "Individual, Solo Modificatoria o Sin Eficacia",
      "timestamp": null
    }
  Query:
    Tipo: Decreto
    Jurisdiccion: Nacional