Attempts: 5
Exception: >-
  System.ArgumentException: Document not found with ID '123456789-0abc-874-0000-4102soterced. (Parameter 'id')
     at Clarius.OpenLaw.Argentina.SaijClient.ReadDocument(String id, HttpClient http) in /_/src/OpenLaw/Argentina/SaijClient.cs:line 172
     at Clarius.OpenLaw.Argentina.SaijClient.LoadAsync(SearchResult item) in /_/src/OpenLaw/Argentina/SaijClient.cs:line 128
     at Clarius.OpenLaw.Argentina.SyncCommand.SyncAction.ExecuteAsync() in /_/src/OpenLaw/Argentina/SyncCommand.cs:line 221
Item:
  Id: 123456789-0abc-874-0000-4102soterced
  ContentType: Legislacion
  DocumentType:
    Code: DEC
    Text: Decreto
  Status: Individual, Solo Modificatoria o Sin Eficacia
  Date: 2014-04-03
  Data:
    document:
      metadata:
        uuid: 123456789-0abc-874-0000-4102soterced
        document-content-type: legislacion
        friendly-url:
          subdomain: decreto
          description: 478-nacional-designacion-transitoria-ministerio-justicia-derechos-humanos-dn20140000478-2014-04-03
      content:
        mecanografico: 20140000478
        jurisdiccion:
          codigo: C
          descripcion: Nacional
          capital: Capital Federal
          id-pais: 11
        numero-norma: 478
        tipo-norma:
          codigo: DEC
          texto: Decreto
        fecha: 2014-04-03
        standard-normativo: DEC C 000478 2014 04 03
        titulo-norma: Designación transitoria en el Ministerio de Justicia y Derechos Humanos
        nombre-coloquial: DECRETO NACIONAL 478/2014
        estado: Individual, Solo Modificatoria o Sin Eficacia
        descriptores:
          descriptor:
          - elegido:
              termino: Ministerio de Justicia y Derechos Humanos
            preferido:
              termino: Ministerio de Justicia
            sinonimos:
              termino:
              - Ministerio de Justicia, Seguridad y Derechos Humanos
              - Ministerio de Justicia de la Nación
              - Ministerio de Justicia y Derechos Humanos
          - elegido:
              termino: Subsecretaría de Coordinación
            preferido:
              termino: Subsecretaría de Coordinación
          - elegido:
              termino: designación transitoria
            preferido:
              termino: Derecho administrativo/Administración Pública/empleo público/agentes de la administración pública/situaciones de revista/personal no permanente/personal transitorio
            sinonimos:
              termino:
              - relación de empleo público
              - personal del Estado
              - agentes de la Administración
              - contratación temporaria
              - agentes transitorios
              - función pública
              - planta transitoria
              - nombramiento provisorio
              - personal del sector público
              - agentes públicos
              - personal de planta temporaria
              - funcionarios y empleados públicos
              - designación transitoria
          suggest:
            termino:
            - personal no permanente
            - agentes de la administración pública
            - agentes de la Administración (agentes de la administración pública)
            - Ministerio de Justicia
            - personal del sector público (agentes de la administración pública)
            - situaciones de revista
            - personal del Estado (agentes de la administración pública)
            - designación transitoria (personal transitorio)
            - nombramiento provisorio (personal transitorio)
            - relación de empleo público (empleo público)
            - funcionarios y empleados públicos (agentes de la administración pública)
            - Derecho administrativo
            - agentes transitorios (personal transitorio)
            - función pública (Administración Pública)
            - Ministerio de Justicia de la Nación (Ministerio de Justicia)
            - Ministerio de Justicia y Derechos Humanos (Ministerio de Justicia)
            - Administración Pública
            - agentes públicos (agentes de la administración pública)
            - personal transitorio
            - personal de planta temporaria (personal no permanente)
            - Ministerio de Justicia, Seguridad y Derechos Humanos (Ministerio de Justicia)
            - Subsecretaría de Coordinación
            - empleo público
            - planta transitoria (personal transitorio)
            - contratación temporaria (personal no permanente)
  Json: >-
    {
      "document": {
        "metadata": {
          "uuid": "123456789-0abc-874-0000-4102soterced",
          "document-content-type": "legislacion",
          "friendly-url": {
            "subdomain": "decreto",
            "description": "478-nacional-designacion-transitoria-ministerio-justicia-derechos-humanos-dn20140000478-2014-04-03"
          }
        },
        "content": {
          "mecanografico": 20140000478,
          "jurisdiccion": {
            "codigo": "C",
            "descripcion": "Nacional",
            "capital": "Capital Federal",
            "id-pais": 11
          },
          "numero-norma": 478,
          "tipo-norma": {
            "codigo": "DEC",
            "texto": "Decreto"
          },
          "fecha": "2014-04-03",
          "standard-normativo": "DEC C 000478 2014 04 03",
          "titulo-norma": "Designación transitoria en el Ministerio de Justicia y Derechos Humanos",
          "nombre-coloquial": "DECRETO NACIONAL 478/2014",
          "estado": "Individual, Solo Modificatoria o Sin Eficacia",
          "descriptores": {
            "descriptor": [
              {
                "elegido": {
                  "termino": "Ministerio de Justicia y Derechos Humanos"
                },
                "preferido": {
                  "termino": "Ministerio de Justicia"
                },
                "sinonimos": {
                  "termino": [
                    "Ministerio de Justicia, Seguridad y Derechos Humanos",
                    "Ministerio de Justicia de la Nación",
                    "Ministerio de Justicia y Derechos Humanos"
                  ]
                }
              },
              {
                "elegido": {
                  "termino": "Subsecretaría de Coordinación"
                },
                "preferido": {
                  "termino": "Subsecretaría de Coordinación"
                },
                "sinonimos": null
              },
              {
                "elegido": {
                  "termino": "designación transitoria"
                },
                "preferido": {
                  "termino": "Derecho administrativo/Administración Pública/empleo público/agentes de la administración pública/situaciones de revista/personal no permanente/personal transitorio"
                },
                "sinonimos": {
                  "termino": [
                    "relación de empleo público",
                    "personal del Estado",
                    "agentes de la Administración",
                    "contratación temporaria",
                    "agentes transitorios",
                    "función pública",
                    "planta transitoria",
                    "nombramiento provisorio",
                    "personal del sector público",
                    "agentes públicos",
                    "personal de planta temporaria",
                    "funcionarios y empleados públicos",
                    "designación transitoria"
                  ]
                }
              }
            ],
            "suggest": {
              "termino": [
                "personal no permanente",
                "agentes de la administración pública",
                "agentes de la Administración (agentes de la administración pública)",
                "Ministerio de Justicia",
                "personal del sector público (agentes de la administración pública)",
                "situaciones de revista",
                "personal del Estado (agentes de la administración pública)",
                "designación transitoria (personal transitorio)",
                "nombramiento provisorio (personal transitorio)",
                "relación de empleo público (empleo público)",
                "funcionarios y empleados públicos (agentes de la administración pública)",
                "Derecho administrativo",
                "agentes transitorios (personal transitorio)",
                "función pública (Administración Pública)",
                "Ministerio de Justicia de la Nación (Ministerio de Justicia)",
                "Ministerio de Justicia y Derechos Humanos (Ministerio de Justicia)",
                "Administración Pública",
                "agentes públicos (agentes de la administración pública)",
                "personal transitorio",
                "personal de planta temporaria (personal no permanente)",
                "Ministerio de Justicia, Seguridad y Derechos Humanos (Ministerio de Justicia)",
                "Subsecretaría de Coordinación",
                "empleo público",
                "planta transitoria (personal transitorio)",
                "contratación temporaria (personal no permanente)"
              ]
            }
          }
        }
      }
    }
  JQ: >-
    {
      "id": "123456789-0abc-874-0000-4102soterced",
      "contentType": "legislacion",
      "documentType": {
        "code": "DEC",
        "text": "Decreto"
      },
      "date": "2014-04-03",
      "status": "Individual, Solo Modificatoria o Sin Eficacia",
      "timestamp": null
    }
  Query:
    Tipo: Decreto
    Jurisdiccion: Nacional