Attempts: 5
Exception: >-
  System.ArgumentException: Document not found with ID '123456789-0abc-542-0000-7102soterced. (Parameter 'id')
     at Clarius.OpenLaw.Argentina.SaijClient.ReadDocument(String id, HttpClient http) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 237
     at Clarius.OpenLaw.Argentina.SaijClient.LoadAsync(SearchResult item) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 193
     at Clarius.OpenLaw.Argentina.SyncAction.ExecuteAsync(SaijClient client, FileDocumentRepository targetRepository, Boolean noDebugger) in /_/src/OpenLaw.Commands/Argentina/SyncAction.cs:line 31
Item:
  Id: 123456789-0abc-542-0000-7102soterced
  ContentType: Legislacion
  DocumentType:
    Code: DEC
    Text: Decreto
  Status: Vigente, de alcance general
  Date: 2017-04-07
  Data:
    document:
      metadata:
        uuid: 123456789-0abc-542-0000-7102soterced
        document-content-type: legislacion
        friendly-url:
          subdomain: decreto
          description: 245-nacional-aprobacion-modelo-acuerdo-otorgamiento-linea-credito-condicional-modelo-contrato-prestamo-banco-interamericano-desarrollo-dn20170000245-2017-04-07
      content:
        mecanografico: 20170000245
        jurisdiccion:
          codigo: C
          descripcion: Nacional
          capital: Capital Federal
          id-pais: 11
        numero-norma: 245
        tipo-norma:
          codigo: DEC
          texto: Decreto
        fecha: 2017-04-07
        standard-normativo: DEC C 000245 2017 04 07
        titulo-norma: Aprobación del Modelo de Acuerdo de Otorgamiento de Línea de Crédito Condicional y Modelo de Contrato de Préstamo con el Banco Interamericano de Desarrollo
        nombre-coloquial: DECRETO NACIONAL 245/2017
        estado: Vigente, de alcance general
        descriptores:
          descriptor:
          - elegido:
              termino: modelo de convenio
            preferido:
              termino: Economía y finanzas/convenios de cooperación/convenios con las provincias/convenio multilateral/modelo de convenio
            sinonimos:
              termino:
              - Hacienda y Finanzas
              - acuerdo de cooperación
              - convenio de colaboración
              - derecho económico financiero
              - convenios con la Nación
              - derecho financiero
          - elegido:
              termino: Banco Interamericano de Desarrollo
            preferido:
              termino: Economía y finanzas/sistema financiero/préstamo internacional/Banco Interamericano de Desarrollo
            sinonimos:
              termino:
              - Hacienda y Finanzas
              - BID
              - derecho económico financiero
              - préstamo bancario internacional
              - derecho financiero
          suggest:
            termino:
            - convenios con las provincias
            - préstamo bancario internacional (préstamo internacional)
            - convenios de cooperación
            - derecho financiero (Economía y finanzas)
            - convenio multilateral
            - derecho económico financiero (Economía y finanzas)
            - sistema financiero
            - modelo de convenio
            - acuerdo de cooperación (convenios de cooperación)
            - Hacienda y Finanzas (Economía y finanzas)
            - convenio de colaboración (convenios de cooperación)
            - préstamo internacional
            - BID (Banco Interamericano de Desarrollo)
            - Banco Interamericano de Desarrollo
            - Economía y finanzas
            - convenios con la Nación (convenios con las provincias)
  Json: >-
    {
      "document": {
        "metadata": {
          "uuid": "123456789-0abc-542-0000-7102soterced",
          "document-content-type": "legislacion",
          "friendly-url": {
            "subdomain": "decreto",
            "description": "245-nacional-aprobacion-modelo-acuerdo-otorgamiento-linea-credito-condicional-modelo-contrato-prestamo-banco-interamericano-desarrollo-dn20170000245-2017-04-07"
          }
        },
        "content": {
          "mecanografico": 20170000245,
          "jurisdiccion": {
            "codigo": "C",
            "descripcion": "Nacional",
            "capital": "Capital Federal",
            "id-pais": 11
          },
          "numero-norma": 245,
          "tipo-norma": {
            "codigo": "DEC",
            "texto": "Decreto"
          },
          "fecha": "2017-04-07",
          "standard-normativo": "DEC C 000245 2017 04 07",
          "titulo-norma": "Aprobación del Modelo de Acuerdo de Otorgamiento de Línea de Crédito Condicional y Modelo de Contrato de Préstamo con el Banco Interamericano de Desarrollo",
          "nombre-coloquial": "DECRETO NACIONAL 245/2017",
          "estado": "Vigente, de alcance general",
          "descriptores": {
            "descriptor": [
              {
                "elegido": {
                  "termino": "modelo de convenio"
                },
                "preferido": {
                  "termino": "Economía y finanzas/convenios de cooperación/convenios con las provincias/convenio multilateral/modelo de convenio"
                },
                "sinonimos": {
                  "termino": [
                    "Hacienda y Finanzas",
                    "acuerdo de cooperación",
                    "convenio de colaboración",
                    "derecho económico financiero",
                    "convenios con la Nación",
                    "derecho financiero"
                  ]
                }
              },
              {
                "elegido": {
                  "termino": "Banco Interamericano de Desarrollo"
                },
                "preferido": {
                  "termino": "Economía y finanzas/sistema financiero/préstamo internacional/Banco Interamericano de Desarrollo"
                },
                "sinonimos": {
                  "termino": [
                    "Hacienda y Finanzas",
                    "BID",
                    "derecho económico financiero",
                    "préstamo bancario internacional",
                    "derecho financiero"
                  ]
                }
              }
            ],
            "suggest": {
              "termino": [
                "convenios con las provincias",
                "préstamo bancario internacional (préstamo internacional)",
                "convenios de cooperación",
                "derecho financiero (Economía y finanzas)",
                "convenio multilateral",
                "derecho económico financiero (Economía y finanzas)",
                "sistema financiero",
                "modelo de convenio",
                "acuerdo de cooperación (convenios de cooperación)",
                "Hacienda y Finanzas (Economía y finanzas)",
                "convenio de colaboración (convenios de cooperación)",
                "préstamo internacional",
                "BID (Banco Interamericano de Desarrollo)",
                "Banco Interamericano de Desarrollo",
                "Economía y finanzas",
                "convenios con la Nación (convenios con las provincias)"
              ]
            }
          }
        }
      }
    }
  JQ: >-
    {
      "id": "123456789-0abc-542-0000-7102soterced",
      "contentType": "legislacion",
      "documentType": {
        "code": "DEC",
        "text": "Decreto"
      },
      "date": "2017-04-07",
      "status": "Vigente, de alcance general",
      "timestamp": null
    }
  Query:
    Tipo: Decreto
    Jurisdiccion: Nacional