Attempts: 5
Exception: >-
  System.ArgumentException: Document not found with ID '123456789-0abc-912-1000-6102soterced. (Parameter 'id')
     at Clarius.OpenLaw.Argentina.SaijClient.ReadDocument(String id, HttpClient http) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 237
     at Clarius.OpenLaw.Argentina.SaijClient.LoadAsync(SearchResult item) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 193
     at Clarius.OpenLaw.Argentina.SyncAction.ExecuteAsync(SaijClient client, FileDocumentRepository targetRepository, Boolean noDebugger) in /_/src/OpenLaw.Commands/Argentina/SyncAction.cs:line 31
Item:
  Id: 123456789-0abc-912-1000-6102soterced
  ContentType: Legislacion
  DocumentType:
    Code: DEC
    Text: Decreto
  Status: Individual, Solo Modificatoria o Sin Eficacia
  Date: 2016-12-01
  Data:
    document:
      metadata:
        uuid: 123456789-0abc-912-1000-6102soterced
        document-content-type: legislacion
        friendly-url:
          subdomain: decreto
          description: 1219-nacional-designacion-director-comision-banco-central-republica-argentina-dn20160001219-2016-12-01
      content:
        mecanografico: 20160001219
        jurisdiccion:
          codigo: C
          descripcion: Nacional
          capital: Capital Federal
          id-pais: 11
        numero-norma: 1219
        tipo-norma:
          codigo: DEC
          texto: Decreto
        fecha: 2016-12-01
        standard-normativo: DEC C 001219 2016 12 01
        titulo-norma: Designación del Director en Comisión del Banco Central de la República Argentina
        nombre-coloquial: DECRETO NACIONAL 1.219/2016
        estado: Individual, Solo Modificatoria o Sin Eficacia
        descriptores:
          descriptor:
          - elegido:
              termino: designación de funcionarios
            preferido:
              termino: Derecho administrativo/Administración Pública/empleo público/ingreso a la función pública/nombramiento
            sinonimos:
              termino:
              - nombramiento de funcionarios
              - nombramiento de empleados públicos
              - nombramiento de funcionarios públicos
              - relación de empleo público
              - función pública
              - designación de funcionarios
              - designación de personal
              - designación
              - designación de funcionarios públicos
          - elegido:
              termino: Banco Central de la República Argentina
            preferido:
              termino: Derecho bancario/entidades financieras/bancos/banco central/Banco Central de la República Argentina
            sinonimos:
              termino:
              - BCRA
              - entidades bancarias
              - sistema bancario
          suggest:
            termino:
            - ingreso a la función pública
            - nombramiento de funcionarios (nombramiento)
            - designación de personal (nombramiento)
            - función pública (Administración Pública)
            - BCRA (Banco Central de la República Argentina)
            - banco central
            - entidades bancarias (bancos)
            - designación de funcionarios públicos (nombramiento)
            - nombramiento
            - designación de funcionarios (nombramiento)
            - Banco Central de la República Argentina
            - Administración Pública
            - nombramiento de funcionarios públicos (nombramiento)
            - nombramiento de empleados públicos (nombramiento)
            - Derecho bancario
            - designación (nombramiento)
            - bancos
            - empleo público
            - entidades financieras
            - sistema bancario (Derecho bancario)
            - relación de empleo público (empleo público)
            - Derecho administrativo
  Json: >-
    {
      "document": {
        "metadata": {
          "uuid": "123456789-0abc-912-1000-6102soterced",
          "document-content-type": "legislacion",
          "friendly-url": {
            "subdomain": "decreto",
            "description": "1219-nacional-designacion-director-comision-banco-central-republica-argentina-dn20160001219-2016-12-01"
          }
        },
        "content": {
          "mecanografico": 20160001219,
          "jurisdiccion": {
            "codigo": "C",
            "descripcion": "Nacional",
            "capital": "Capital Federal",
            "id-pais": 11
          },
          "numero-norma": 1219,
          "tipo-norma": {
            "codigo": "DEC",
            "texto": "Decreto"
          },
          "fecha": "2016-12-01",
          "standard-normativo": "DEC C 001219 2016 12 01",
          "titulo-norma": "Designación del Director en Comisión del Banco Central de la República Argentina",
          "nombre-coloquial": "DECRETO NACIONAL 1.219/2016",
          "estado": "Individual, Solo Modificatoria o Sin Eficacia",
          "descriptores": {
            "descriptor": [
              {
                "elegido": {
                  "termino": "designación de funcionarios"
                },
                "preferido": {
                  "termino": "Derecho administrativo/Administración Pública/empleo público/ingreso a la función pública/nombramiento"
                },
                "sinonimos": {
                  "termino": [
                    "nombramiento de funcionarios",
                    "nombramiento de empleados públicos",
                    "nombramiento de funcionarios públicos",
                    "relación de empleo público",
                    "función pública",
                    "designación de funcionarios",
                    "designación de personal",
                    "designación",
                    "designación de funcionarios públicos"
                  ]
                }
              },
              {
                "elegido": {
                  "termino": "Banco Central de la República Argentina"
                },
                "preferido": {
                  "termino": "Derecho bancario/entidades financieras/bancos/banco central/Banco Central de la República Argentina"
                },
                "sinonimos": {
                  "termino": [
                    "BCRA",
                    "entidades bancarias",
                    "sistema bancario"
                  ]
                }
              }
            ],
            "suggest": {
              "termino": [
                "ingreso a la función pública",
                "nombramiento de funcionarios (nombramiento)",
                "designación de personal (nombramiento)",
                "función pública (Administración Pública)",
                "BCRA (Banco Central de la República Argentina)",
                "banco central",
                "entidades bancarias (bancos)",
                "designación de funcionarios públicos (nombramiento)",
                "nombramiento",
                "designación de funcionarios (nombramiento)",
                "Banco Central de la República Argentina",
                "Administración Pública",
                "nombramiento de funcionarios públicos (nombramiento)",
                "nombramiento de empleados públicos (nombramiento)",
                "Derecho bancario",
                "designación (nombramiento)",
                "bancos",
                "empleo público",
                "entidades financieras",
                "sistema bancario (Derecho bancario)",
                "relación de empleo público (empleo público)",
                "Derecho administrativo"
              ]
            }
          }
        }
      }
    }
  JQ: >-
    {
      "id": "123456789-0abc-912-1000-6102soterced",
      "contentType": "legislacion",
      "documentType": {
        "code": "DEC",
        "text": "Decreto"
      },
      "date": "2016-12-01",
      "status": "Individual, Solo Modificatoria o Sin Eficacia",
      "timestamp": null
    }
  Query:
    Tipo: Decreto
    Jurisdiccion: Nacional