Attempts: 5
Exception: >-
  System.ArgumentException: Document not found with ID '123456789-0abc-263-0000-4102soterced. (Parameter 'id')
     at Clarius.OpenLaw.Argentina.SaijClient.ReadDocument(String id, HttpClient http) in /_/src/OpenLaw/Argentina/SaijClient.cs:line 172
     at Clarius.OpenLaw.Argentina.SaijClient.LoadAsync(SearchResult item) in /_/src/OpenLaw/Argentina/SaijClient.cs:line 128
     at Clarius.OpenLaw.Argentina.SyncCommand.SyncAction.ExecuteAsync() in /_/src/OpenLaw/Argentina/SyncCommand.cs:line 221
Item:
  Id: 123456789-0abc-263-0000-4102soterced
  ContentType: Legislacion
  DocumentType:
    Code: DEC
    Text: Decreto
  Status: Individual, Solo Modificatoria o Sin Eficacia
  Date: 2014-03-25
  Data:
    document:
      metadata:
        uuid: 123456789-0abc-263-0000-4102soterced
        document-content-type: legislacion
        friendly-url:
          subdomain: decreto
          description: 362-nacional-designacion-unidad-ministro-dn20140000362-2014-03-25
      content:
        mecanografico: 20140000362
        jurisdiccion:
          codigo: C
          descripcion: Nacional
          capital: Capital Federal
          id-pais: 11
        numero-norma: 362
        tipo-norma:
          codigo: DEC
          texto: Decreto
        fecha: 2014-03-25
        standard-normativo: DEC C 000362 2014 03 25
        titulo-norma: Designación en la Unidad Ministro
        nombre-coloquial: DECRETO NACIONAL 362/2014
        estado: Individual, Solo Modificatoria o Sin Eficacia
        descriptores:
          descriptor:
          - elegido:
              termino: Ministerio de Ciencia, Tecnología e Innovación Productiva
            preferido:
              termino: Ministerio de Ciencia, Tecnología e Innovación Productiva
          - elegido:
              termino: designación
            preferido:
              termino: Derecho administrativo/Administración Pública/empleo público/ingreso a la función pública/nombramiento
            sinonimos:
              termino:
              - nombramiento de funcionarios
              - nombramiento de empleados públicos
              - nombramiento de funcionarios públicos
              - relación de empleo público
              - función pública
              - designación de funcionarios
              - designación de personal
              - designación
              - designación de funcionarios públicos
          suggest:
            termino:
            - ingreso a la función pública
            - nombramiento de funcionarios (nombramiento)
            - designación de personal (nombramiento)
            - función pública (Administración Pública)
            - Ministerio de Ciencia, Tecnología e Innovación Productiva
            - designación de funcionarios públicos (nombramiento)
            - nombramiento
            - designación de funcionarios (nombramiento)
            - Administración Pública
            - nombramiento de funcionarios públicos (nombramiento)
            - nombramiento de empleados públicos (nombramiento)
            - designación (nombramiento)
            - empleo público
            - relación de empleo público (empleo público)
            - Derecho administrativo
  Json: >-
    {
      "document": {
        "metadata": {
          "uuid": "123456789-0abc-263-0000-4102soterced",
          "document-content-type": "legislacion",
          "friendly-url": {
            "subdomain": "decreto",
            "description": "362-nacional-designacion-unidad-ministro-dn20140000362-2014-03-25"
          }
        },
        "content": {
          "mecanografico": 20140000362,
          "jurisdiccion": {
            "codigo": "C",
            "descripcion": "Nacional",
            "capital": "Capital Federal",
            "id-pais": 11
          },
          "numero-norma": 362,
          "tipo-norma": {
            "codigo": "DEC",
            "texto": "Decreto"
          },
          "fecha": "2014-03-25",
          "standard-normativo": "DEC C 000362 2014 03 25",
          "titulo-norma": "Designación en la Unidad Ministro",
          "nombre-coloquial": "DECRETO NACIONAL 362/2014",
          "estado": "Individual, Solo Modificatoria o Sin Eficacia",
          "descriptores": {
            "descriptor": [
              {
                "elegido": {
                  "termino": "Ministerio de Ciencia, Tecnología e Innovación Productiva"
                },
                "preferido": {
                  "termino": "Ministerio de Ciencia, Tecnología e Innovación Productiva"
                },
                "sinonimos": null
              },
              {
                "elegido": {
                  "termino": "designación"
                },
                "preferido": {
                  "termino": "Derecho administrativo/Administración Pública/empleo público/ingreso a la función pública/nombramiento"
                },
                "sinonimos": {
                  "termino": [
                    "nombramiento de funcionarios",
                    "nombramiento de empleados públicos",
                    "nombramiento de funcionarios públicos",
                    "relación de empleo público",
                    "función pública",
                    "designación de funcionarios",
                    "designación de personal",
                    "designación",
                    "designación de funcionarios públicos"
                  ]
                }
              }
            ],
            "suggest": {
              "termino": [
                "ingreso a la función pública",
                "nombramiento de funcionarios (nombramiento)",
                "designación de personal (nombramiento)",
                "función pública (Administración Pública)",
                "Ministerio de Ciencia, Tecnología e Innovación Productiva",
                "designación de funcionarios públicos (nombramiento)",
                "nombramiento",
                "designación de funcionarios (nombramiento)",
                "Administración Pública",
                "nombramiento de funcionarios públicos (nombramiento)",
                "nombramiento de empleados públicos (nombramiento)",
                "designación (nombramiento)",
                "empleo público",
                "relación de empleo público (empleo público)",
                "Derecho administrativo"
              ]
            }
          }
        }
      }
    }
  JQ: >-
    {
      "id": "123456789-0abc-263-0000-4102soterced",
      "contentType": "legislacion",
      "documentType": {
        "code": "DEC",
        "text": "Decreto"
      },
      "date": "2014-03-25",
      "status": "Individual, Solo Modificatoria o Sin Eficacia",
      "timestamp": null
    }
  Query:
    Tipo: Decreto
    Jurisdiccion: Nacional