Attempts: 5
Exception: >-
  System.ArgumentException: Document not found with ID '123456789-0abc-532-0000-7102soterced. (Parameter 'id')
     at Clarius.OpenLaw.Argentina.SaijClient.ReadDocument(String id, HttpClient http) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 237
     at Clarius.OpenLaw.Argentina.SaijClient.LoadAsync(SearchResult item) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 193
     at Clarius.OpenLaw.Argentina.SyncAction.ExecuteAsync(SaijClient client, FileDocumentRepository targetRepository, Boolean noDebugger) in /_/src/OpenLaw.Commands/Argentina/SyncAction.cs:line 31
Item:
  Id: 123456789-0abc-532-0000-7102soterced
  ContentType: Legislacion
  DocumentType:
    Code: DEC
    Text: Decreto
  Status: Vigente, de alcance general
  Date: 2017-04-06
  Data:
    document:
      metadata:
        uuid: 123456789-0abc-532-0000-7102soterced
        document-content-type: legislacion
        friendly-url:
          subdomain: decreto
          description: 235-nacional-modelo-contratos-bid-dn20170000235-2017-04-06
      content:
        mecanografico: 20170000235
        jurisdiccion:
          codigo: C
          descripcion: Nacional
          capital: Capital Federal
          id-pais: 11
        numero-norma: 235
        tipo-norma:
          codigo: DEC
          texto: Decreto
        fecha: 2017-04-06
        standard-normativo: DEC C 000235 2017 04 06
        titulo-norma: Modelo de Contratos BID
        nombre-coloquial: DECRETO NACIONAL 235/2017
        estado: Vigente, de alcance general
        descriptores:
          descriptor:
          - elegido:
              termino: contratos
            preferido:
              termino: Derecho civil/derechos personales/contratos
            sinonimos:
              termino: obligaciones y contratos
          - elegido:
              termino: BID
            preferido:
              termino: Economía y finanzas/sistema financiero/préstamo internacional/Banco Interamericano de Desarrollo
            sinonimos:
              termino:
              - Hacienda y Finanzas
              - BID
              - derecho económico financiero
              - préstamo bancario internacional
              - derecho financiero
          suggest:
            termino:
            - préstamo bancario internacional (préstamo internacional)
            - derecho financiero (Economía y finanzas)
            - derecho económico financiero (Economía y finanzas)
            - sistema financiero
            - Hacienda y Finanzas (Economía y finanzas)
            - obligaciones y contratos (derechos personales)
            - préstamo internacional
            - BID (Banco Interamericano de Desarrollo)
            - contratos
            - derechos personales
            - Derecho civil
            - Banco Interamericano de Desarrollo
            - Economía y finanzas
  Json: >-
    {
      "document": {
        "metadata": {
          "uuid": "123456789-0abc-532-0000-7102soterced",
          "document-content-type": "legislacion",
          "friendly-url": {
            "subdomain": "decreto",
            "description": "235-nacional-modelo-contratos-bid-dn20170000235-2017-04-06"
          }
        },
        "content": {
          "mecanografico": 20170000235,
          "jurisdiccion": {
            "codigo": "C",
            "descripcion": "Nacional",
            "capital": "Capital Federal",
            "id-pais": 11
          },
          "numero-norma": 235,
          "tipo-norma": {
            "codigo": "DEC",
            "texto": "Decreto"
          },
          "fecha": "2017-04-06",
          "standard-normativo": "DEC C 000235 2017 04 06",
          "titulo-norma": "Modelo de Contratos BID",
          "nombre-coloquial": "DECRETO NACIONAL 235/2017",
          "estado": "Vigente, de alcance general",
          "descriptores": {
            "descriptor": [
              {
                "elegido": {
                  "termino": "contratos"
                },
                "preferido": {
                  "termino": "Derecho civil/derechos personales/contratos"
                },
                "sinonimos": {
                  "termino": "obligaciones y contratos"
                }
              },
              {
                "elegido": {
                  "termino": "BID"
                },
                "preferido": {
                  "termino": "Economía y finanzas/sistema financiero/préstamo internacional/Banco Interamericano de Desarrollo"
                },
                "sinonimos": {
                  "termino": [
                    "Hacienda y Finanzas",
                    "BID",
                    "derecho económico financiero",
                    "préstamo bancario internacional",
                    "derecho financiero"
                  ]
                }
              }
            ],
            "suggest": {
              "termino": [
                "préstamo bancario internacional (préstamo internacional)",
                "derecho financiero (Economía y finanzas)",
                "derecho económico financiero (Economía y finanzas)",
                "sistema financiero",
                "Hacienda y Finanzas (Economía y finanzas)",
                "obligaciones y contratos (derechos personales)",
                "préstamo internacional",
                "BID (Banco Interamericano de Desarrollo)",
                "contratos",
                "derechos personales",
                "Derecho civil",
                "Banco Interamericano de Desarrollo",
                "Economía y finanzas"
              ]
            }
          }
        }
      }
    }
  JQ: >-
    {
      "id": "123456789-0abc-532-0000-7102soterced",
      "contentType": "legislacion",
      "documentType": {
        "code": "DEC",
        "text": "Decreto"
      },
      "date": "2017-04-06",
      "status": "Vigente, de alcance general",
      "timestamp": null
    }
  Query:
    Tipo: Decreto
    Jurisdiccion: Nacional