Attempts: 5
Exception: >-
  System.ArgumentException: Invalid document data'. (Parameter 'json')
     at Clarius.OpenLaw.Argentina.Document.ParseAsync(String json) in /_/src/OpenLaw.Commands/Argentina/Document.cs:line 50
     at Clarius.OpenLaw.Argentina.SaijClient.ReadDocument(String id, HttpClient http) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 248
     at Clarius.OpenLaw.Argentina.SaijClient.LoadAsync(SearchResult item) in /_/src/OpenLaw.Commands/Argentina/SaijClient.cs:line 193
     at Clarius.OpenLaw.Argentina.SyncAction.ExecuteAsync(SaijClient client, FileDocumentRepository targetRepository, Boolean noDebugger) in /_/src/OpenLaw.Commands/Argentina/SyncAction.cs:line 31
Item:
  Id: 123456789-0abc-203-0001-3891soterced
  ContentType: Legislacion
  DocumentType:
    Code: DEC
    Text: Decreto
  Status: Vigente, de alcance general
  Date: 1983-02-08
  Timestamp: 20251211115058
  Data:
    document:
      metadata:
        uuid: 123456789-0abc-203-0001-3891soterced
        document-content-type: legislacion
        friendly-url:
          subdomain: decreto
          description: 302-nacional-decreto-reglamentario-ley-20429-armas-explosivos-dn19831000302-1983-02-08
      content:
        mecanografico: 19831000302
        jurisdiccion:
          codigo: C
          descripcion: Nacional
          capital: Capital Federal
          id-pais: 11
        numero-norma: 302
        tipo-norma:
          codigo: DEC
          texto: Decreto
        fecha: 1983-02-08
        standard-normativo: DEC C 000302 1983 02 08
        titulo-norma: DECRETO REGLAMENTARIO DE LA LEY 20.429 DE ARMAS Y EXPLOSIVOS.
        publicacion-codificada:
          publicacion-decodificada:
            organismo: Boletín Oficial
            fecha: 1983 02 28
        nombre-coloquial: DECRETO NACIONAL 302/1983
        estado: Vigente, de alcance general
        descriptores:
          descriptor:
          - elegido:
              termino: decreto reglamentario
            preferido:
              termino: Derecho administrativo/acto administrativo/acto administrativo de alcance general/reglamentos/decreto reglamentario
            sinonimos:
              termino:
              - reglamento ejecutivo
              - actos de alcance general
              - reglamento de ejecución
              - reglamento administrativo
          - elegido:
              termino: explosivos
            preferido:
              termino: Defensa y seguridad/armas/explosivos
            sinonimos:
              termino: defensa nacional
          - elegido:
              termino: registro nacional de armas
            preferido:
              termino: Defensa y seguridad/armas/registro de armas/registro nacional de armas
            sinonimos:
              termino: defensa nacional
          - elegido:
              termino: explosiones
            preferido:
              termino: explosiones
          - elegido:
              termino: importaciones
            preferido:
              termino: Derecho tributario y aduanero/Derecho Aduanero/comercio exterior/operaciones aduaneras/importaciones
            sinonimos:
              termino: comercio internacional
          - elegido:
              termino: exportaciones
            preferido:
              termino: Derecho tributario y aduanero/Derecho Aduanero/comercio exterior/operaciones aduaneras/exportaciones
            sinonimos:
              termino: comercio internacional
          - elegido:
              termino: pirotecnia
            preferido:
              termino: Defensa y seguridad/armas/explosivos/pirotecnia
            sinonimos:
              termino: defensa nacional
          - elegido:
              termino: Gendarmería Nacional
            preferido:
              termino: Defensa y seguridad/seguridad pública/fuerzas de seguridad/Gendarmería Nacional
            sinonimos:
              termino:
              - seguridad nacional
              - defensa nacional
              - personal de seguridad
          - elegido:
              termino: Prefectura Naval
            preferido:
              termino: Defensa y seguridad/seguridad pública/fuerzas de seguridad/Prefectura Naval
            sinonimos:
              termino:
              - seguridad nacional
              - defensa nacional
              - Prefectura naval Argentina
              - personal de seguridad
          - elegido:
              termino: policía federal
            preferido:
              termino: Defensa y seguridad/seguridad pública/fuerzas de seguridad/policía/policía federal
            sinonimos:
              termino:
              - seguridad nacional
              - defensa nacional
              - Policía Federal Argentina
              - personal de seguridad
          - elegido:
              termino: policía territorial
            preferido:
              termino: Defensa y seguridad/seguridad pública/fuerzas de seguridad/policía/policía territorial
            sinonimos:
              termino:
              - seguridad nacional
              - defensa nacional
              - personal de seguridad
          - elegido:
              termino: Policía Provincial
            preferido:
              termino: Defensa y seguridad/seguridad pública/fuerzas de seguridad/policía/Policía Provincial
            sinonimos:
              termino:
              - seguridad nacional
              - defensa nacional
              - personal de seguridad
          suggest:
            termino:
            - Derecho Aduanero
            - operaciones aduaneras
            - decreto reglamentario
            - reglamento de ejecución (decreto reglamentario)
            - reglamento ejecutivo (decreto reglamentario)
            - reglamentos
            - Derecho tributario y aduanero
            - comercio internacional (comercio exterior)
            - personal de seguridad (fuerzas de seguridad)
            - Defensa y seguridad
            - registro de armas
            - fuerzas de seguridad
            - Gendarmería Nacional
            - policía territorial
            - comercio exterior
            - Policía Provincial
            - policía federal
            - acto administrativo de alcance general
            - explosiones
            - reglamento administrativo (reglamentos)
            - policía
            - Derecho administrativo
            - Prefectura Naval
            - defensa nacional (Defensa y seguridad)
            - Policía Federal Argentina (policía federal)
            - exportaciones
            - explosivos
            - armas
            - pirotecnia
            - seguridad pública
            - acto administrativo
            - Prefectura naval Argentina (Prefectura Naval)
            - actos de alcance general (acto administrativo de alcance general)
            - registro nacional de armas
            - seguridad nacional (seguridad pública)
            - importaciones
        fecha-umod: 20251211115058
  Json: >-
    {
      "document": {
        "metadata": {
          "uuid": "123456789-0abc-203-0001-3891soterced",
          "document-content-type": "legislacion",
          "friendly-url": {
            "subdomain": "decreto",
            "description": "302-nacional-decreto-reglamentario-ley-20429-armas-explosivos-dn19831000302-1983-02-08"
          }
        },
        "content": {
          "mecanografico": 19831000302,
          "jurisdiccion": {
            "codigo": "C",
            "descripcion": "Nacional",
            "capital": "Capital Federal",
            "id-pais": 11
          },
          "numero-norma": 302,
          "tipo-norma": {
            "codigo": "DEC",
            "texto": "Decreto"
          },
          "fecha": "1983-02-08",
          "standard-normativo": "DEC C 000302 1983 02 08",
          "titulo-norma": "DECRETO REGLAMENTARIO DE LA LEY 20.429 DE ARMAS Y EXPLOSIVOS.",
          "publicacion-codificada": {
            "publicacion-decodificada": {
              "organismo": "Boletín Oficial",
              "fecha": "1983 02 28"
            }
          },
          "nombre-coloquial": "DECRETO NACIONAL 302/1983",
          "estado": "Vigente, de alcance general",
          "descriptores": {
            "descriptor": [
              {
                "elegido": {
                  "termino": "decreto reglamentario"
                },
                "preferido": {
                  "termino": "Derecho administrativo/acto administrativo/acto administrativo de alcance general/reglamentos/decreto reglamentario"
                },
                "sinonimos": {
                  "termino": [
                    "reglamento ejecutivo",
                    "actos de alcance general",
                    "reglamento de ejecución",
                    "reglamento administrativo"
                  ]
                }
              },
              {
                "elegido": {
                  "termino": "explosivos"
                },
                "preferido": {
                  "termino": "Defensa y seguridad/armas/explosivos"
                },
                "sinonimos": {
                  "termino": "defensa nacional"
                }
              },
              {
                "elegido": {
                  "termino": "registro nacional de armas"
                },
                "preferido": {
                  "termino": "Defensa y seguridad/armas/registro de armas/registro nacional de armas"
                },
                "sinonimos": {
                  "termino": "defensa nacional"
                }
              },
              {
                "elegido": {
                  "termino": "explosiones"
                },
                "preferido": {
                  "termino": "explosiones"
                },
                "sinonimos": null
              },
              {
                "elegido": {
                  "termino": "importaciones"
                },
                "preferido": {
                  "termino": "Derecho tributario y aduanero/Derecho Aduanero/comercio exterior/operaciones aduaneras/importaciones"
                },
                "sinonimos": {
                  "termino": "comercio internacional"
                }
              },
              {
                "elegido": {
                  "termino": "exportaciones"
                },
                "preferido": {
                  "termino": "Derecho tributario y aduanero/Derecho Aduanero/comercio exterior/operaciones aduaneras/exportaciones"
                },
                "sinonimos": {
                  "termino": "comercio internacional"
                }
              },
              {
                "elegido": {
                  "termino": "pirotecnia"
                },
                "preferido": {
                  "termino": "Defensa y seguridad/armas/explosivos/pirotecnia"
                },
                "sinonimos": {
                  "termino": "defensa nacional"
                }
              },
              {
                "elegido": {
                  "termino": "Gendarmería Nacional"
                },
                "preferido": {
                  "termino": "Defensa y seguridad/seguridad pública/fuerzas de seguridad/Gendarmería Nacional"
                },
                "sinonimos": {
                  "termino": [
                    "seguridad nacional",
                    "defensa nacional",
                    "personal de seguridad"
                  ]
                }
              },
              {
                "elegido": {
                  "termino": "Prefectura Naval"
                },
                "preferido": {
                  "termino": "Defensa y seguridad/seguridad pública/fuerzas de seguridad/Prefectura Naval"
                },
                "sinonimos": {
                  "termino": [
                    "seguridad nacional",
                    "defensa nacional",
                    "Prefectura naval Argentina",
                    "personal de seguridad"
                  ]
                }
              },
              {
                "elegido": {
                  "termino": "policía federal"
                },
                "preferido": {
                  "termino": "Defensa y seguridad/seguridad pública/fuerzas de seguridad/policía/policía federal"
                },
                "sinonimos": {
                  "termino": [
                    "seguridad nacional",
                    "defensa nacional",
                    "Policía Federal Argentina",
                    "personal de seguridad"
                  ]
                }
              },
              {
                "elegido": {
                  "termino": "policía territorial"
                },
                "preferido": {
                  "termino": "Defensa y seguridad/seguridad pública/fuerzas de seguridad/policía/policía territorial"
                },
                "sinonimos": {
                  "termino": [
                    "seguridad nacional",
                    "defensa nacional",
                    "personal de seguridad"
                  ]
                }
              },
              {
                "elegido": {
                  "termino": "Policía Provincial"
                },
                "preferido": {
                  "termino": "Defensa y seguridad/seguridad pública/fuerzas de seguridad/policía/Policía Provincial"
                },
                "sinonimos": {
                  "termino": [
                    "seguridad nacional",
                    "defensa nacional",
                    "personal de seguridad"
                  ]
                }
              }
            ],
            "suggest": {
              "termino": [
                "Derecho Aduanero",
                "operaciones aduaneras",
                "decreto reglamentario",
                "reglamento de ejecución (decreto reglamentario)",
                "reglamento ejecutivo (decreto reglamentario)",
                "reglamentos",
                "Derecho tributario y aduanero",
                "comercio internacional (comercio exterior)",
                "personal de seguridad (fuerzas de seguridad)",
                "Defensa y seguridad",
                "registro de armas",
                "fuerzas de seguridad",
                "Gendarmería Nacional",
                "policía territorial",
                "comercio exterior",
                "Policía Provincial",
                "policía federal",
                "acto administrativo de alcance general",
                "explosiones",
                "reglamento administrativo (reglamentos)",
                "policía",
                "Derecho administrativo",
                "Prefectura Naval",
                "defensa nacional (Defensa y seguridad)",
                "Policía Federal Argentina (policía federal)",
                "exportaciones",
                "explosivos",
                "armas",
                "pirotecnia",
                "seguridad pública",
                "acto administrativo",
                "Prefectura naval Argentina (Prefectura Naval)",
                "actos de alcance general (acto administrativo de alcance general)",
                "registro nacional de armas",
                "seguridad nacional (seguridad pública)",
                "importaciones"
              ]
            }
          },
          "fecha-umod": 20251211115058
        }
      }
    }
  JQ: >-
    {
      "id": "123456789-0abc-203-0001-3891soterced",
      "contentType": "legislacion",
      "documentType": {
        "code": "DEC",
        "text": "Decreto"
      },
      "date": "1983-02-08",
      "status": "Vigente, de alcance general",
      "timestamp": 20251211115058
    }
  Query:
    Tipo: Decreto
    Jurisdiccion: Nacional