# Sincroniza leyes y decretos nacionales en este repositorio
name: diario-vigentes
on:
  workflow_dispatch:
    inputs:
      syncArgs:
        description: 'Opciones de sync (por ej. --vigente, --force)'
        required: false
        type: string
        default: ''
  schedule:
    - cron: "0 22 * * 1-5" # Lu-Vie 19hs

env:
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: pwsh

jobs:
  run:
    uses: ./.github/workflows/sync.yml
    permissions: 
      contents: write
      pull-requests: write
    with:
      options: --vigente