# Sincroniza leyes y decretos nacionales en este repositorio
name: semanal-completo
on:
  workflow_dispatch:
    inputs:
      options:
        description: 'Opciones de sync (por ej. --vigente, --force, --top)'
        required: false
        type: string
        default: ''
  schedule:
    - cron: "0 22 * * 6" # Sábados 19hs 

env:
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: pwsh

jobs:
  run:
    uses: ./.github/workflows/sync.yml
    permissions: 
      contents: write
      pull-requests: write
    secrets: inherit
    with: 
      options: ${{ github.event.inputs.options }}